### ISSUE TITLE
关于番号命名和分片刮削

### ISSUE THREAD

**Issue by joker-nan** [Yuukiy/JavSP#1]
谢谢分享这么好的项目
下面是我使用中的问题和处理方法

我尝试了开箱即用的文件  发现刮削后标题文件以番号开头会造成媒体库比较乱,再媒体库    然后我尝试自己构建，编辑 nfo 18和20行 info.dvdid + ' ' + info.title  替换成 info.title + '[' info.dvdid ']'  在保留番号的情况下  使媒体库较为清晰

**Comment by Yuukiy** [comment]
改进了一下，现在可以和文件命名一样，使用自定义的模板来控制nfo中的影片标题了 abb4638
