### ISSUE TITLE
希望适配centos

### ISSUE THREAD

**Issue by AuroraFrowned** [Yuukiy/JavSP#101]
### 功能建议

希望适配centos
还是很多在用linux命令行，可以考虑删减一些功能然后发布

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by harvey-git** [comment]
大哥，这玩意儿基于python3，默认就是支持命令行的啊：`python3 JavSP.py -i  要整理的路径`

**Comment by Yuukiy** [comment]
Linux平台可以基于源码运行，未进行完整测试不过大多数功能应该是可用的
