### ISSUE TITLE
复活fc2club现域名为fc2club.top

### ISSUE THREAD

**Issue by qq1052983095** [Yuukiy/JavSP#103]
### 功能建议

我已复活fc2club.com，现域名为fc2club.top，和原站数据一致,截至到FC2-1470000以前，支持抓取，感谢诸位大佬辛苦开发工具

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Polemo1024** [comment]
> 

你好，请问可以分享下fc2的备份文件吗

**Comment by Yuukiy** [comment]
感谢支持，不过似乎只能打开首页，而不能打开具体的影片页面

**Comment by Yuukiy** [comment]
目前站点能打开，已添加支持
