### ISSUE TITLE
因为PT需要做种，如何只搜刮，不重命名呢？

### ISSUE THREAD

**Issue by Fanglongzong** [Yuukiy/JavSP#104]
### 功能建议

因为PT需要做种，如何只搜刮，不重命名呢？

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by zhouzikk** [comment]
自己做硬链接

**Comment by oxorangeone** [comment]
应该也可以随便找个视频文件改下命名，毕竟刮削看的是视频的标题，根本不会管视频实质是什么，刮削好了把数据丢过去

**Comment by VergilGao** [comment]
举个栗子：
如果你用的是 QB，下载目录是 /downloads 
完全可以在下载完成时运行外部程序里添加如下命令。
```
cp -lR "%F" /downloads/complete
```
这样就会自动硬链接你下载完成的文件到complete目录。
