### ISSUE TITLE
多cd的片源，封面搜刮问题

### ISSUE THREAD

**Issue by kingsnakerrr** [Yuukiy/JavSP#107]
### 问题详情

多cd的片源，封面搜刮问题，例如2cd的片源，不会搜刮出一个-poster.jpg（可以识别）或者WANZ-086-poster.jpg（这个不知道会不会识别，看你文档是会生成这样的封面格式）的封面图片，会搜刮出WANZ-086-CD1-poster.jpg和WANZ-086-CD1-poster.jpg。plex不会识别封面。

# 配置整理时的命名规则
# save_dir, nfo_title和filename中可以使用变量来引用影片的数据，支持的变量列表见下面的地址:
# https://github.com/Yuukiy/JavSP/wiki/NamingRule-%7C-%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99
[NamingRule]
# 设置媒体服务器类型
media_servers = plex
# 整理后的影片和封面等文件的保存位置
output_folder = #整理完成
# 存放影片、封面等文件的文件夹路径
save_dir = $actress/[$num] $title
# 影片、封面、nfo信息文件等的文件名将基于下面的规则来创建
filename = $num

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/10187211/JavSP.log)

### 运行截图（可选）

![image](https://user-images.githubusercontent.com/48008289/206497387-cd2646b5-05d1-4f4c-8fc5-5d8a752a985d.png)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
需要一个师爷来帮我翻译翻译
