### ISSUE TITLE
希望可以增加Linux版本

### ISSUE THREAD

**Issue by Nolovenodie** [Yuukiy/JavSP#11]
如题 可以方便在Linux服务器上执行

**Comment by Yuukiy** [comment]
有考虑提供多平台版本的，但是后面看开发情况吧，当前用户也不多，用Linux的可能就更少了。着急的话可以Fork一下先改着用

**Comment by KSOYU** [comment]
jellyfin用户想要docker版

**Comment by Losalkki** [comment]
从repuirments来看，有两个依赖会阻碍迁移：例如pywin32-ctypes==0.2.0

**Comment by winniesi** [comment]
非常感谢有这么好用的脚本！我也有在群晖跑的需求，打算最近改造在 Linux 下直接跑

**Comment by Yuukiy** [comment]
> 非常感谢有这么好用的脚本！我也有在群晖跑的需求，打算最近改造在 Linux 下直接跑

期待~欢迎发PullRequest~
