### ISSUE TITLE
整理失败: [WinError 123] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by Doorgy** [Yuukiy/JavSP#119]
### 问题详情

整理过程命名失败

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/12519048/JavSP.log)

### 运行截图（可选）

![Snipaste_2023-09-05_13-17-36](https://github.com/Yuukiy/JavSP/assets/72721533/dfa3d036-c326-40ba-8472-56cbb54cd32b)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
我这里验证没有复现

![image](https://github.com/Yuukiy/JavSP/assets/76897913/184b6619-d9b3-46ea-8871-35f98ad242c2)

看你的日志，你这是远程文件系统映射到本地？（比如NAS）如果是的话：
- 远程主机是什么系统？
- 通过什么协议共享文件到本地的？（比如WebDAV/smb或者其他）

**Comment by ChiotOnAGE** [comment]
应该是和这个有关吧 #8. 只支持 256 byte 长度文件名的文件系统还是挺多的，详见 [Wiki](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). 目前是按照 character 数目计算的，在 Windows 上应该没问题，因为 NTFS 好像是按照 UTF-16 计算 character 数的，如果要把跨平台搞定，感觉还是要在配置中应该区分一下是按照 byte 计算还是某种编码的 character 计算。

**Comment by Yuukiy** [comment]
@ChiotOnAGE 更新了一版，你试试能不能用，我就不去搞zfs文件系统了
如果需要exe的话可以到这里 https://github.com/Yuukiy/JavSP/suites/16004035300/artifacts/913584470

**Comment by Doorgy** [comment]
是威联通NAS映射本地的，我自己手动试了下，确实是命名长度问题导致的

**Comment by Yuukiy** [comment]
看起来解决了？我先关闭ticket了
