### ISSUE TITLE
建议增加过滤文件大小条件

### ISSUE THREAD

**Issue by poplarxyz** [Yuukiy/JavSP#120]
### 功能建议

部分磁链带推广视频触发“下列番号对应多部影片文件且不符合分片规则”，直接以文件大小条件过滤比正则匹配更适用。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by 1zhouzhou** [comment]
感觉这是个伪需求呢，个人建议用”everything“拉出所有的视频，大小排序删掉那些推广视频。本来它们的命运就应该进垃圾桶，对吧

**Comment by rongcc1985** [comment]
我也有这个需求，支持下

**Comment by rongcc1985** [comment]
我今天折腾了半天，终于解决这个问题了：
用aria2下载，可以设置文件大小小于xx的文件会自动删除。
我设置成50m，然后最后就会只剩1个主文件来刮削。
