### ISSUE TITLE
无法识别MKBD-S125

### ISSUE THREAD

**Issue by nightdawnex** [Yuukiy/JavSP#123]
### 问题详情

https://javmenu.com/en/MKBD-S125

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

无法提取影片番号: '\bt\MKBD-S125.mp4'

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
单例不修

**Comment by 1zhouzhou** [comment]
这个问题我也出现了，番号名为MKBD-S75，不太清楚问题出在哪里，用的是1.42版。作者可以用这几个热门资源的番号做一下测试MKBD-S108，MKBD-S113，MKBD-S03，MKBD-S75；这些番号在javbus都可以搜索到。
