### ISSUE TITLE
百度翻译网址错误

### ISSUE THREAD

**Issue by FruitLoopsmxd** [Yuukiy/JavSP#127]
### 问题详情

百度翻译开放平台地址已变为http://api.fanyi.baidu.com/ 原地址报错

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你是新注册的百度翻译么？我这里使用旧的API接口还是正常的
![image](https://github.com/Yuukiy/JavSP/assets/76897913/26d5e422-e5a7-42ed-9cc9-6070933d6054)
