### ISSUE TITLE
建议可以增加https://av-wiki.net/ 这个站的刮削

### ISSUE THREAD

**Issue by 1zhouzhou** [Yuukiy/JavSP#132]
### 功能建议

这个网站收录有大量所谓”素人“ ”企划“影片，比如”マジ軟派、初撮“ , "募集ちゃん ～求む。一般素人女性～"等等。
再比如著名的企划美女单体作品 ”259LUXU“系列，这个系列的番号已经接近2000，其中不乏知名女优，比如白咲りの（259LUXU-592，259LUXU-593），森日向子（259LUXU-1438），愛音まりあ（259LUXU-752），不过这个系列从不用女优的常用艺名，而是换一个新名字，这也是此系列的一个特色。这个网站很好的记录还原了她们的常用艺名。此站可以完美查找相关资料并匹配正确的女优艺名。非常好用。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
这个网站似乎没有封面和预览图？

**Comment by Yuukiy** [comment]
另外我看这个站点实际是链接到fanza和mgstage，而这两个站点已经有对应的抓取支持了。av-wiki会保留下架的影片的信息么？如果不会，那av-wiki能搜到的在fanza和mgstage上应该也能搜到

**Comment by 1zhouzhou** [comment]
> 另外我看这个站点实际是链接到fanza和mgstage，而这两个站点已经有对应的抓取支持了。av-wiki会保留下架的影片的信息么？如果不会，那av-wiki能搜到的在fanza和mgstage上应该也能搜到

影片的图片资源基本都是链接的外站，所以如果外站删资料肯定看不到，不过这个avwiki站点的页面肯定不会删。此站点其实不止你提到的2个站点，建议使用“白咲りの”这个女优在av-wiki搜索，此女优的作品情况比较典型，她在很多小众厂牌下都有出演。使用过茫茫多的艺名，MGS和fanza都无法抓取到白咲りの这个最常见艺名，我觉得这是此站点最有价值的地方，是否值得爬取还看作者你的考虑。还有一个案例是“浅見せな”。游历各大片商，有很多艺名。如果没有很高的价值，可以忽略。
ps 顺便感谢一下作者，辛苦维护和分享。如果有什么需要帮助的，我可以帮忙，不过我不会python，会的比较杂，PS，前端UI，搜索能力也还行，主要是平时时间比较多。最近一直在建立自己的库。

**Comment by Yuukiy** [comment]
添加了 (https://github.com/Yuukiy/JavSP/commit/4dbcdbe4f5cb507316a5feaf5c0aa00ba7363d21)
