### ISSUE TITLE
完全无法刮削

### ISSUE THREAD

**Issue by OdinShiva** [Yuukiy/JavSP#139]
### 问题详情

<img width="786" alt="image" src="https://github.com/Yuukiy/JavSP/assets/27851197/5f98ad17-3d57-4da2-91a2-2ec1f85a8a74">

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 运行截图（可选）

<img width="786" alt="image" src="https://github.com/Yuukiy/JavSP/assets/27851197/7c63ac86-c6bf-4102-b232-88fad7127885">

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by OdinShiva** [comment]
[JavSP.log](https://github.com/Yuukiy/JavSP/files/13420469/JavSP.log)

**Comment by Yuukiy** [comment]
【我确认使用的是最新版本并且阅读过Wiki帮助文档】
