### ISSUE TITLE
[feature] 希望能够支持gyutto的av刮削

### ISSUE THREAD

**Issue by miechidandao** [Yuukiy/JavSP#14]
gyutto网站上也有着许多类似于fc2的同人r18视频，（https://gyutto.com/）
可以通过检索日文名称来实现视频快照的访问，不知道作者是否有意愿，先谢过了

**Comment by Yuukiy** [comment]
没太明白。。。
我去看了网站，似乎多数影片没有唯一的编号？如果只通过名字搜索匹配的话正确率应该会非常低，而且与现在的工作模式不兼容。部分影片有编号，如 http://gyutto.com/i/item246713?select_uaflag=1 ，但是也能在现有的网站上找到 https://javdb.com/v/9GRKX

**Comment by Yuukiy** [comment]
又重新想了一下这个问题，现在好像有点可以曲线救国的思路。不过由于没有准确的ID，所以必须要人为介入的：需要你为每一部影片确认item编号（使用地址栏的item编号作为影片编号），比如`http://gyutto.com/i/`**item239001**。
你要是觉得还需要这个功能，提供几部你下载好的影片的文件名、文件夹结构（如果有特殊结构）给我吧。可以使用```tree /f /a```显示文件夹的结构

**Comment by miechidandao** [comment]
其实没有特别的结构要求，只是想整理gyutto的影片更方便一些，我这边有大概几十部比如：item114140，item206519，item241872.mp4

**Comment by Yuukiy** [comment]
> 其实没有特别的结构要求，只是想整理gyutto的影片更方便一些，我这边有大概几十部比如：item114140，item206519，item241872.mp4

你下载好的影片原始文件名就是这样的名字么？因为你之前提到的是用日文名称搜索，我以为你下载好的影片是日文名的。

如果下载好的影片是日文名的，那你提供几部影片的原始**文件**名字给我吧。如果下载好就是这样的item编号，那就不用了。

**Comment by Yuukiy** [comment]
> 其实没有特别的结构要求，只是想整理gyutto的影片更方便一些，我这边有大概几十部比如：item114140，item206519，item241872.mp4

特殊结构主要是指影片本体的名字没有特征，番号或者影片名要从文件夹名称或者别的地方获取的那种，比如这种：
```
ちょっと足りない？小さな女の子\movie.mp4
```

**Comment by miechidandao** [comment]
害那没事了，我本来是想着整理的时候方便点，感觉这些片本来的名称几乎没有什么特征，唯一的共性就是能在[itemxxxxxx](http://gyutto.com/i/itemxxxxxx)上面找到

**Comment by Yuukiy** [comment]
那我关闭issue啦，之前一直没关是想着看后面有没有别的可能方法和时间。
