### ISSUE TITLE
1.5版本无法爬取，提示“为其配置的8个抓取器均未获取到影片信息”

### ISSUE THREAD

**Issue by 1zhouzhou** [Yuukiy/JavSP#143]
### 问题详情

未改动ini配置文件，重新下载的1.5版，代理地址为日本，全局。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/13466334/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by lanceli93** [comment]
Same issue here, 1.4 works perfect

**Comment by 1zhouzhou** [comment]
> Same issue here, 1.4 works perfect

1.42 works perfect. Thank u for the tip, bro. Cheers.
