### ISSUE TITLE
对一些老番号的刮削存在问题，想跟作者大大交流一下

### ISSUE THREAD

**Issue by 1zhouzhou** [Yuukiy/JavSP#144]
### 问题详情

PB-25，（女优白石），在javbus可搜索到，log显示“main:85 DEBUG: web.javbus: 未找到影片: 'PB-25'”；
MKD-S75，在javbus可搜索到，log显示“无法提取影片番号”。
从log中判断，这两个番号无法刮削的原因应该不一样。是bug还是什么其他问题，作者大大有空看一看。我已手动刮削。
感谢作者的无私分享。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
JavBus的`PB-25`番号为`PB-025`，你的影片也要为这个番号才行
`MKD-S75`这样的番号暂时不支持识别（`-`后面还有字母）
