### ISSUE TITLE
airav站点无法刮削

### ISSUE THREAD

**Issue by sqx626** [Yuukiy/JavSP#151]
### 问题详情

直接访问网站可以正常访问，代理节点换过，错误日志“HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/STARS-160?lng=zh-TW')”

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/13528116/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你试一下 2d84bd99de5bd6eacda83fab0bd4390729e9f58b 这个版本 https://github.com/Yuukiy/JavSP/suites/18909028910/artifacts/1104281456

**Comment by Yuukiy** [comment]
无后续反馈
