### ISSUE TITLE
我们可以变成英语吗？

### ISSUE THREAD

**Issue by sisounthone14** [Yuukiy/JavSP#156]
### 功能建议

如果可能的话，我想用英语写NFO和标题。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
Most of the original data sites are in traditional Chinese or Japanese, with few options available in English. To generate an English nfo file for your project, you may need to fork this project and modify the target language (the argument `to` in code) for translation in the code.
- Google Translate
https://github.com/Yuukiy/JavSP/blob/34f30f696f99929fc1e9de0173cbf1bb22c70945/web/translate.py#L154
- Bing Translate
https://github.com/Yuukiy/JavSP/blob/34f30f696f99929fc1e9de0173cbf1bb22c70945/web/translate.py#L116

**Comment by sisounthone14** [comment]
i tried changing  [def google_trans(texts, to='en'): ]
but i get error google: 429: Too Many Requests

**Comment by Yuukiy** [comment]
I tried it, and it seems to be working
![image](https://github.com/Yuukiy/JavSP/assets/76897913/d5e13ee3-fe9b-4996-b54b-86d5929181a7)
Can you try accessing Google with a different IP? (for example, using a proxy) The 429 error indicates that your IP has sent too many requests to Google.

**Comment by Yuukiy** [comment]
I've added a waiting mechanism for 'too many requests' in Google Translate. You can try the new version f2a91069d27d0043153bbc310ffce47ead66b2c7

**Comment by sisounthone14** [comment]
hello
i tried its working. but i dont understand. 
it just translate only the plot.
![image](https://github.com/Yuukiy/JavSP/assets/152849015/4da28467-95c4-44b1-a09a-8e1f7099f32a)
![image](https://github.com/Yuukiy/JavSP/assets/152849015/e64caf81-4adb-4603-8bc1-e5cfb5edca86)

**Comment by sisounthone14** [comment]
Is it because it modify the config.ini wrongly?

**Comment by sisounthone14** [comment]
alright thank you

**Comment by Yuukiy** [comment]
It depends on the number of English users and the progress of other features. As you know, there are still many features to be developed.
