### ISSUE TITLE
网盘挂载电脑上的视频无法整理

### ISSUE THREAD

**Issue by ghost** [Yuukiy/JavSP#158]
### 问题详情

我是用alist+Raidrive把迅雷云盘挂载到了本地，运行程序会显示“整理失败:[WinError 5] 拒绝访问”。请问这种情况如何处理呢？

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/13612818/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by aodai2000** [comment]
我网上搜了下方法，在本地D盘做了软链接，好像还是不行
<img width="283" alt="1" src="https://github.com/Yuukiy/JavSP/assets/153277823/3b426628-1c82-4d35-8f52-6918a68746c7">

**Comment by aodai2000** [comment]
> 先将网盘文件生成软链接（类似于快捷方式），再对软链接操作

我查了下教程，做了一个软链接放到本地D盘，对D盘里的软链接操作好像还是不行
![Uploading 1.png…]()

**Comment by Yuukiy** [comment]
RaiDrive挂载到本地应该会产生一个盘符的，你在那个盘符里找到你的迅雷网盘，然后直接在里面尝试新建文件、移动文件、重命名文件，看下会不会报错？

**Comment by aodai2000** [comment]
好的感谢！应该是我操作上有些问题，后面我再尝试看看。
