### ISSUE TITLE
增加一个32位版本的可执行文件

### ISSUE THREAD

**Issue by kudingc** [Yuukiy/JavSP#168]
### 功能建议

老哥是怎么编译的啊？我想整个32位版本的，但是编译不出来你那样的可执行文件

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你下载一个32位版本的python，安装完相关库再打包成exe，出来的就是32位版本了

**Comment by kudingc** [comment]
> 你下载一个32位版本的python，安装完相关库再打包成exe，出来的就是32位版本了

我就是这样做的，但是编译不出来你那样的，你是怎么编译的啊？
