### ISSUE TITLE
1.6选择路径后闪退

### ISSUE THREAD

**Issue by XingXing-404** [Yuukiy/JavSP#169]
### 问题详情

100%复现，运行路径和指定路径均为SMB挂载路径，在1.5.1使用正常，切换为1.6更新后报错。
配置如下：
[config.txt](https://github.com/Yuukiy/JavSP/files/13703355/config.txt)

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/13703313/JavSP.log)

### 运行截图（可选）

<img width="784" alt="image" src="https://github.com/Yuukiy/JavSP/assets/132803533/af5f76de-5873-4623-9763-2cbfea6349b5">

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
@XingXing-404  紧急修复了一下 (v1.6.1)，应该已经好了，你试试

**Comment by Yuukiy** [comment]
紧急修复了一下 (v1.6.1)，应该已经好了，你试试

**Comment by Yuukiy** [comment]
无后续反馈
