### ISSUE TITLE
有cd1、cd2这种分集情况下，jellyfin无法识别到封面图

### ISSUE THREAD

**Issue by lyklll** [Yuukiy/JavSP#17]
经测试，如果文件名是 xxxx-cd1.avi;xxxx-cd2.avi。。。。
那么将 xxxx-poster.jpg 更名为 xxxx-cd1-poster.jpg 即可；
期待修复这个问题~

**Comment by Yuukiy** [comment]
已于 df2f4f2a 增加对应处理机制。近期不会发布0.7，可以到 https://github.com/Yuukiy/JavSP/actions/runs/1552718099 下载临时释放版测试使用

**Comment by Yuukiy** [comment]
无后续反馈。自测已修复
