### ISSUE TITLE
部分番号自动机翻成中文名

### ISSUE THREAD

**Issue by Lemongith** [Yuukiy/JavSP#175]
### 问题详情

这个问题我在1.5.1，1.6.1 上可以复现，还没有试别的版本。
config.ini上面已经禁用了翻译，但是有的番号还是自动机翻（log 里面已经获取了日文翻译）。
正常番号 - "MIDE-233"
可复现问题的番号 - “MIDE-213” 

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/13726988/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你上传的日志：
1. 是 v1.4.1 版本的
2. 没有出现你说的问题

**Comment by Yuukiy** [comment]
无反馈
