### ISSUE TITLE
请问能否增加一个把剧情简介也加入到NFO中的功能

### ISSUE THREAD

**Issue by JacobLi97** [Yuukiy/JavSP#182]
### 功能建议

请问能否增加一个把剧情简介也加入到NFO中

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
已有此功能 https://github.com/Yuukiy/JavSP/blob/master/core/nfo.py#L33
