### ISSUE TITLE
希望生成女优头像地址url，还有解决相同女优有不同名字的问题

### ISSUE THREAD

**Issue by xtanke** [Yuukiy/JavSP#183]
### 功能建议

第一个请求顾名思义。

第二个问题举个例子
会同时存在（篠田優和篠田ゆう）两个文件夹

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
1. 在能够直接从影片页面获得女优头像时，会生成对应的URL，比如javbus。如果你想要全女优头像，建议使用 https://github.com/gfriends/gfriends
2. https://github.com/Yuukiy/JavSP/issues/167

**Comment by xtanke** [comment]
我确实找到了一个头像插件，现在就只剩下todo的多名字问题了，不过别人已经提交过了。谢谢
