### ISSUE TITLE
多个分集超过10个不能被识别

### ISSUE THREAD

**Issue by csmx1234** [Yuukiy/JavSP#184]
### 问题详情

多个分集以-CD结尾超过10个不能被识别

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

2024-01-02 20:39:05 core.file:127 ERROR: 下列番号对应多部影片文件且不符合分片规则，已略过整理，请手动处理后重新运行脚本: 
VRKM-700: 
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD1.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD10.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD2.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD3.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD4.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD5.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD6.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD7.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD8.mp4
  JAV_output\新村あかり, 桜庭ひかり, 渚みつき, 吉根ゆりあ, 永野つかさ, 東條なつ, 白桃はな, 有岡みう, 辻さくら, 天然美月\VRKM-700\VRKM-700-CD9.mp4

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
还真有超过10个的分片啊😂但是许多媒体服务器也是不支持太多分片的，比如
emby是9个
https://emby.media/support/articles/Movie-Naming.html#split-video-files-file-stacking
plex是8个
https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/
