### ISSUE TITLE
中文繁体内容转换为简体

### ISSUE THREAD

**Issue by mx1700** [Yuukiy/JavSP#187]
### 功能建议

希望能把标题、tag、简介里的内容从繁体转换为简体。
用 OpenCC 库应该用不了多少代码，如果需要我可以贡献代码。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
那可太需要了😎

**Comment by mx1700** [comment]
> 那可太需要了😎

我需要再看一下代码，目前我没有很好的办法判断内容是日文还是繁体中文，我只知道目前分类应该都是繁体中文的，可以直接转换。标题和简介有可能是日文，有可能是中文，直接判断并不容易，在考虑是否引入判断语言的库。

**Comment by Yuukiy** [comment]
> > 那可太需要了😎
> 
> 我需要再看一下代码，目前我没有很好的办法判断内容是日文还是繁体中文，我只知道目前分类应该都是繁体中文的，可以直接转换。标题和简介有可能是日文，有可能是中文，直接判断并不容易，在考虑是否引入判断语言的库。

分类(genre)原本是准备手动维护的，因为有些类别，比如“DVD多士炉”，让人一头雾水😂后来维护不动鸽了
