### ISSUE TITLE
S2MBD系列被识别为MBD系列

### ISSUE THREAD

**Issue by Joey0217** [Yuukiy/JavSP#191]
### 问题详情

S2MBD系列无法正确识别
如：S2MBD-007 無碼 安可 7 : 波多野結衣，JAVDB中有此番号
被识别为 MBD-007 萌えあがる募集若妻 淫らに狂い出す身売りわかづま 7 ゆみさん，JAVLib

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 运行截图（可选）

<img width="671" alt="image" src="https://github.com/Yuukiy/JavSP/assets/36755962/30fff49d-5a98-479b-8ba7-91c110de9254">

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
没有对不常规的`S2MBD`做特别处理导致的，话说这个系列有什么规律么？比如有没有`S3MBD`、`S4MBD`或者`S2ABC`啥的

**Comment by Joey0217** [comment]
> 没有对不常规的`S2MBD`做特别处理导致的，话说这个系列有什么规律么？比如有没有`S3MBD`、`S4MBD`或者`S2ABC`啥的

抱歉，我也不太清楚，我试下波多老师的片子，找到这个系列的
