### ISSUE TITLE
期望能够开发可以在Linux下使用的版本

### ISSUE THREAD

**Issue by zhengweiqing** [Yuukiy/JavSP#193]
### 功能建议

期望能够开发可以在Linux下使用的版本，现在的版本在linux下运行会提示出错：
module 'ctypes' has no attribute 'windll'

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
Duplicate https://github.com/Yuukiy/JavSP/issues/24
