### ISSUE TITLE
下载高清封面不会生效

### ISSUE THREAD

**Issue by 784746292** [Yuukiy/JavSP#195]
### 问题详情

这个功能是失效了吗，还是哪里设置不对

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[Uploading FileMove.log…]()

### 运行截图（可选）

![WeChatcfdc3f3ffc7f78e4cfe77629bae2ec57](https://github.com/Yuukiy/JavSP/assets/85598608/6f3bf4c3-a78f-4093-9dcc-d775f89cdb6e)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
寻找高清封面的途径失效了
