### ISSUE TITLE
能否加一个根据文件名称识别标签，如字幕，无码的功能

### ISSUE THREAD

**Issue by grimm-yh** [Yuukiy/JavSP#196]
### 功能建议

能否加一个根据文件名称识别标签，如字幕，无码的功能，比如ipzz-xxx-C, 就可以认识标签为字幕，ipzz-xxx-U就可以认识为无码，ipzz-xxx-UC就是无码and字幕

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
已有

**Comment by Yuukiy** [comment]
```log
扫描影片文件...
扫描影片文件：共找到 1 部影片

正在整理: IPX-177-UC.mp4
重命名文件: 'IPX-177-UC.mp4' -> '...\IPX-177-UC.mp4'
整理完成，相关文件已保存到: #整理完成\相沢みなみ\[IPX-177-UC] 生意気な妹にニーハイを履かせ僕だけの「絶対領域」を誕生させ僕好みに痴女らせた。

请按任意键继续. . .
```
![image](https://github.com/Yuukiy/JavSP/assets/76897913/5c271e0a-bafd-45bc-97b9-e01f365af99c)

**Comment by grimm-yh** [comment]
![微信截图_20240118203815](https://github.com/Yuukiy/JavSP/assets/33012083/624e1022-902a-4ccd-a559-7460f49b1b2a)
可以像这种直接显示在海报上吗

**Comment by Yuukiy** [comment]
Duplicate https://github.com/Yuukiy/JavSP/issues/73
