### ISSUE TITLE
希望可以新增只刮削演员选项

### ISSUE THREAD

**Issue by yuchengyangE** [Yuukiy/JavSP#198]
### 功能建议

每一部都要手动删除导演信息，刮削不到头像很难受
![image](https://github.com/Yuukiy/JavSP/assets/63194233/3b00b61b-a5c1-4f63-960c-4f5cd22a19d4)

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
这种要求我还是第一次见到.jpg

你复制一份代码，注释掉core/nfo.py中的下面两行就行
https://github.com/Yuukiy/JavSP/blob/3f5b726a2601ef21f35cb166575a97e0cc8b2d1a/core/nfo.py#L74-L75

**Comment by yuchengyangE** [comment]
多谢
