### ISSUE TITLE
为什么我的emby和jellyfin识别不出nfo

### ISSUE THREAD

**Issue by uorzen** [Yuukiy/JavSP#2]
emby显示不出来刮削后的影片，jellyfin是能读出文件夹来，但识别不了影片。我猜和nfo文件有关系

**Comment by uorzen** [comment]
我今天把nfo按可以刮削的影片重建了一下  还是不行  搞不清楚问题出现在哪里

**Comment by Yuukiy** [comment]
不识别影片还是不识别nfo信息？是只有emby不行还是jellyfin和emby都不行？

**Comment by uorzen** [comment]
> 不识别影片还是不识别nfo信息？是只有emby不行还是jellyfin和emby都不行？

emby是影片都识别不出来.jellyfin能识别出来影片但是没有刮削信息

**Comment by Yuukiy** [comment]
整理完成后的文件夹里都有哪些文件？要是有nfo文件的话能否提供一下？

**Comment by uorzen** [comment]
![IMG_20210424_165817](https://user-images.githubusercontent.com/21340039/115953496-70807200-a51e-11eb-8fdb-5cdada5b55d0.jpg)

**Comment by uorzen** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
  <title>MIDE-223 タイトスカート女教師 西田カリナ</title>
  <runtime>150</runtime>
  <mpaa>NC-17</mpaa>
  <uniqueid type="num" defult="true">MIDE-223</uniqueid>
  <genre>單體作品</genre>
  <genre>DMM獨家</genre>
  <genre>蕩婦</genre>
  <genre>女教師</genre>
  <genre>屁股</genre>
  <genre>姐姐</genre>
  <genre>戀腿癖</genre>
  <genre>數位馬賽克</genre>
  <genre>高畫質</genre>
  <tag>單體作品</tag>
  <tag>DMM獨家</tag>
  <tag>蕩婦</tag>
  <tag>女教師</tag>
  <tag>屁股</tag>
  <tag>姐姐</tag>
  <tag>戀腿癖</tag>
  <tag>數位馬賽克</tag>
  <tag>高畫質</tag>
  <country>日本</country>
  <set>
    <name>タイトスカート女教師</name>
  </set>
  <directr>麒麟</directr>
  <premiered>2015-04-11</premiered>
  <studio>ムーディーズ</studio>
  <actor>
    <name>西田カリナ</name>
    <thumb>https://pics.javcdn.net/actress/myq_a.jpg</thumb>
  </actor>
</movie>

**Comment by uorzen** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
  <title>MIDE-223 タイトスカート女教師 西田カリナ</title>
  <runtime>150</runtime>
  <mpaa>NC-17</mpaa>
  <uniqueid type="num" defult="true">MIDE-223</uniqueid>
  <genre>單體作品</genre>
  <genre>DMM獨家</genre>
  <genre>蕩婦</genre>
  <genre>女教師</genre>
  <genre>屁股</genre>
  <genre>姐姐</genre>
  <genre>戀腿癖</genre>
  <genre>數位馬賽克</genre>
  <genre>高畫質</genre>
  <tag>單體作品</tag>
  <tag>DMM獨家</tag>
  <tag>蕩婦</tag>
  <tag>女教師</tag>
  <tag>屁股</tag>
  <tag>姐姐</tag>
  <tag>戀腿癖</tag>
  <tag>數位馬賽克</tag>
  <tag>高畫質</tag>
  <country>日本</country>
  <set>
    <name>タイトスカート女教師</name>
  </set>
  <directr>麒麟</directr>
  <premiered>2015-04-11</premiered>
  <studio>ムーディーズ</studio>
  <actor>
    <name>西田カリナ</name>
    <thumb>https://pics.javcdn.net/actress/myq_a.jpg</thumb>
  </actor>
</movie>
`

**Comment by uorzen** [comment]
> 整理完成后的文件夹里都有哪些文件？要是有nfo文件的话能否提供一下？

手机nfo传不上来   截个图给你看下  这是其中一个

**Comment by Yuukiy** [comment]
我在我这里试了一下，就同一部影片，能生成nfo，Jellyfin也能识别影片和nfo。。。你的nfo看着也正常的啊。。。

**Comment by uorzen** [comment]
> 我在我这里试了一下，就同一部影片，能生成nfo，Jellyfin也能识别影片和nfo。。。你的nfo看着也正常的啊。。。

我也对比了  确实没什么问题  路径也来会也换过好几回  就是不行

**Comment by uorzen** [comment]
> 我在我这里试了一下，就同一部影片，能生成nfo，Jellyfin也能识别影片和nfo。。。你的nfo看着也正常的啊。。。

我重新用javsdt刮了一遍就好了

**Comment by uorzen** [comment]
> > 我在我这里试了一下，就同一部影片，能生成nfo，Jellyfin也能识别影片和nfo。。。你的nfo看着也正常的啊。。。
> 
> 我重新用javsdt刮了一遍就好了

不知道什么问题
