### ISSUE TITLE
希望改进对多分段影片例如-CD1 -CD2 对EMBY的支持

### ISSUE THREAD

**Issue by nicbest** [Yuukiy/JavSP#202]
目前遇到的情况是：比方遇到一个视频xx-cd1.mp4、 xx-cd2.mp4，刮削过后此文件夹下的文件是xx-cd1.mp4、 xx-cd2.mp4、movie.nfo、poster、fanart，这几个文件，然后EMBY里面CD1不能正常显示封面以及影片信息，反而点开下面的附加部分CD2可以正常显示封面以及影片信息

**Comment by Yuukiy** [comment]
工作正常
![image](https://github.com/Yuukiy/JavSP/assets/76897913/13c76bdc-b35d-4876-80b7-2db6d865ad16)

**Comment by cedarmissing** [comment]
我的也是这种情况，总是默认选择cd2作为主文件
![iShot2024-09-11 20 12 45](https://github.com/user-attachments/assets/068c578b-6abc-429c-8af7-b331fc1224c9)
![iShot2024-09-11 20 16 50](https://github.com/user-attachments/assets/54a90bbb-1720-4811-b041-34ba052b3eb8)

**Comment by karasfjm** [comment]
> 我的也是这种情况，总是默认选择cd2作为主文件 ![iShot2024-09-11 20 12 45](https://github.com/user-attachments/assets/068c578b-6abc-429c-8af7-b331fc1224c9) ![iShot2024-09-11 20 16 50](https://github.com/user-attachments/assets/54a90bbb-1720-4811-b041-34ba052b3eb8)

我度过各种办法，先只留CD1，但是把CD2复制进去后还是会变成主视频，最后想了个笨办法，把CD1和CD2互换，然后元数据把CD1改成CD2
