### ISSUE TITLE
希望将日志文件分割为单个文件

### ISSUE THREAD

**Issue by lfcz** [Yuukiy/JavSP#203]
### 功能建议

目前的日志都存储在JavSP.log内，多次大量进行刮削后日志太多太杂乱。如果可以每次运行是以时间戳或者日期为名保存到log目录下的单独log文件可能效果会更好

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
各有优劣吧，对于需要看日志的用户，日期分隔会方便查找一些。对于不需要看日志或者没有概念的用户，日期分隔会让文件夹里充满日志。

给看到issue的其他朋友，如果你也需要这个功能，请为这个issue点 👍
