### ISSUE TITLE
是否源码模式可以用一些公共库？而不是win系统下的库？

### ISSUE THREAD

**Issue by zhengweiqing** [Yuukiy/JavSP#204]
### 功能建议

现在linux源码方式运行会提示：module 'ctypes' has no attribute 'windll'，能否引用一些公共类库，这样就可以直接linux了。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
待办事项里一直有……就是没有变成已办……

**Comment by zw1031977306** [comment]
> 待办事项里一直有……就是没有变成已办……

@Yuukiy 什么情况下需要encode一下？我试了自己的映射盘，读取出来的还是带盘符的路径，并没有计算路径前面的IP或者域名。

**Comment by tatete** [comment]
> 待办事项里一直有……就是没有变成已办……

@Yuukiy  什么情况下需要encode一下？我试了自己的映射盘，读取出来的还是带盘符的路径，并没有计算路径前面的IP或者域名。

**Comment by tatete** [comment]
> > 待办事项里一直有……就是没有变成已办……
> 
> @Yuukiy 什么情况下需要encode一下？我试了自己的映射盘，读取出来的还是带盘符的路径，并没有计算路径前面的IP或者域名。

知道为啥了，我去改了试试看
