### ISSUE TITLE
filename = $num命名规则无效

### ISSUE THREAD

**Issue by graycz** [Yuukiy/JavSP#208]
### 问题详情

看wiki的介绍，使用filename = $num命名规则时，文件应该是：
  ├─君色花音,四ツ葉うらら,関根奈美,音ノ木さくら,七瀬萌,ななせ麻衣
  │  └─[SQTE-196] 引き締まった美体があまりに敏感な美少女のSEX事情
  │          SQTE-196-fanart.jpg
  │          SQTE-196-poster.jpg
  │          SQTE-196.mp4
  │          SQTE-196.nfo
但我实际用下来是
  │          fanart.jpg
  │          poster.jpg
  │          SQTE-196.mp4
  │          movie.nfo
图片和nfo文件没有番号

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/14128409/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
把配置文件里的`media_servers`改为`jellyfin`
