### ISSUE TITLE
相同影片分片檔案能用回該原始檔名嗎?

### ISSUE THREAD

**Issue by AlphaVitaMan** [Yuukiy/JavSP#213]
### 问题详情

首先感謝大大用心製作, 造福群眾.

我在轉換一些有分片的影片時(如: AQUGA-003-B, AQUGA-003-C 或 MDVR-264-4, MDVR-264-7) 都會出現如提示

「
下列番号对应多部影片文件且不符合分片规则，已略过整理，请手动处理后重新运行脚本:
MDVR-264:
  MDVR-264-4.mp4
  MDVR-264-7.mp4

未找到影片文件
」

但當我轉換由1開始順序的分片檔就沒此問題, 分片檔名重名命為CD1, CD2... 因為圖片檔沒有番號之分, 如果把整個資料夾放在emby上, 就不能正確讀取分片.

單一檔案時也沒有此問題, 但是就會重新命名檔案成沒有影片分片編號( MDVR-264-4.mp4 -> MDVR-264.mp4), 

1. 關於不連續的分片請問有沒有解決方法?
2. 請問能否不移除分片編號, 直接用回原有檔名? 

先行謝過.

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
添加了分片编号的检查主要是担心有用户可能在不同的子目录里存了同一影片的分片和不分片版本，或者直接接受不连续的分片时可能导致整理后编号错乱。你的两个问题，现在都是不支持的。
不过你什么场景下需要用到不连续的分片呢？只想保留某个分片节省空间？如果只是因为解决emby不识别分片的问题，可以改一下设置:
`media_servers = universal`
这样的设置是最大兼容性的设置，emby应该能识别的

**Comment by Yuukiy** [comment]
这个功能感觉很偏门我就不做了，你如果需要的话可以试着fork之后自己改一下

https://github.com/Yuukiy/JavSP/blob/master/core/file.py#L113
