### ISSUE TITLE
[WinError 17] 系統無法將檔案移到不同的磁碟機。

### ISSUE THREAD

**Issue by sliverlin** [Yuukiy/JavSP#214]
### 问题详情

刮削沒問題但是在整理檔案時出現異常，來源和輸出目錄都是smb網路硬盤(兩個不同硬盤)
假如我事先把檔案放到同一個盤的話是可以正常整理
想詢問是否有什麼方式可以跨盤整理~感謝

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 运行截图（可选）

![螢幕擷取畫面 2024-02-14 015351](https://github.com/Yuukiy/JavSP/assets/39355740/4d921f82-d993-4a13-8aee-0c6c62ada55e)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你试试下面这个版本有没有修复这个问题
https://github.com/Yuukiy/JavSP/actions/runs/7897944849/artifacts/1243972168

**Comment by sliverlin** [comment]
解決了，感謝!
