### ISSUE TITLE
google翻译频繁触发限制，更换参数和添加延迟避免429

### ISSUE THREAD

**Issue by abmiues** [Yuukiy/JavSP#216]
### 功能建议

在使用默认google翻译时，翻译十几次后就会返回429，修改源码后，将url改为https://translate.google.com.hk/translate_a/single?client=gtx&dt=t&dj=1&ie=UTF-8&sl=auto&tl={to}&q={texts}，且sleep 4秒后，稳定翻译完所有

### 提交须知

- [x] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by zcq100** [comment]
使用本地ollama api没有调用限制。

**Comment by yanrui77** [comment]
具体怎么操作，源码怎么改，config.ini里面无法改吗

**Comment by abmiues** [comment]
> 具体怎么操作，源码怎么改，config.ini里面无法改吗

修改web目录的translate.py，修改google_trans方法中的url为上面的url，在方法的return 前添加 time.sleep(4)
![image](https://github.com/Yuukiy/JavSP/assets/14009148/149d4dbb-3db7-40e9-af74-2c2430acf871)

**Comment by yanrui77** [comment]
小白表示看不懂，大神能否详细说说，win版本下面只有exe没看到web目录

**Comment by abmiues** [comment]
> 小白表示看不懂，大神能否详细说说，win版本下面只有exe没看到web目录

是要改源码。releases里下载源码解压，修改web目录里的translate.py，安装python，用python运行脚本javsp.py，源码的配置文件在core目录里config.ini，

**Comment by yanrui77** [comment]
闪退，是不是需要依赖，新装的py

**Comment by abmiues** [comment]
> 闪退，是不是需要依赖，新装的py

参考readme中的安装，换python3.8，进入解压后的目录，执行pip install -r requirements.txt

**Comment by zoefarm** [comment]
> > 闪退，是不是需要依赖，新装的py
> 
> 参考readme中的安装，换成python3.8，进入解压后的目录，执行pip install -r requirements.txt
老哥 我按你的步骤卡到用python运行脚本javsp.py这里 电脑小白 头都大了
![1719830346422](https://github.com/Yuukiy/JavSP/assets/174298606/bc94b501-6339-4f57-8acf-d420422ee558)

**Comment by abmiues** [comment]
> > > 闪退，是不是需要依赖，新装的py
> > 
> > 
> > 参考readme中的安装，换成python3.8，进入解压后的目录，执行pip install -r requirements.txt
> > 老哥 我按你的步骤卡到用python运行脚本javsp.py这里 电脑小白 头都大了
> > ![1719830346422](https://private-user-images.githubusercontent.com/174298606/344644761-bc94b501-6339-4f57-8acf-d420422ee558.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDkwNzYsIm5iZiI6MTcyMDc0ODc3NiwicGF0aCI6Ii8xNzQyOTg2MDYvMzQ0NjQ0NzYxLWJjOTRiNTAxLTYzMzktNGY1Ny04YWNmLWQ0MjA0MjJlZTU1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDFhMGNlNzg1MzlmYTVmMmU1Njk5ZmMwODE4ZDBhYzU0NWIwMzM1NDliNzcwMjcyOGM0M2NmOTc3M2MzYTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qDgEQCHKPQwWPdVEPMT-L74Gfd5z7vfwiikJuKTgqw8)

根据安装步骤安装依赖了吗？另外这是用py 3.8安装的，最好用py3.8跑
![image](https://github.com/user-attachments/assets/09aa94cd-2f5d-40f1-84e5-64bc7695b9bf)

**Comment by abmiues** [comment]
> 感谢老哥，为什么我这边翻译之后是繁体中文了，是应为挂了香港代理的原因吗
和代理无关。参数中tl={to}中的to是目标语言，从源码来看默认是简中，如果都是繁中，可尝试直接不从to中获取目标语言，即tl={to}改成tl=zh_CN
