### ISSUE TITLE
群晖能挂载 自动挂削吗 

### ISSUE THREAD

**Issue by wangqi12323** [Yuukiy/JavSP#22]
群晖能挂载 自动挂削吗 源代码可以在群晖上用吗

**Comment by Yuukiy** [comment]
你如果能把群晖的硬盘映射到windows就可以。我没有NAS设备，不确定代码直接在群晖上用有没有兼容问题

**Comment by Yuukiy** [comment]
预计能够通过Linux版做到兼容群晖 #11
