### ISSUE TITLE
CTNOZ系列无法自动抓取到信息

### ISSUE THREAD

**Issue by moenimei** [Yuukiy/JavSP#220]
### 功能建议

CTNOZ系列（例如CTNOZ194）可以在getchu查到并手动转换成getchu-id来进行整理，希望可以自动转换或保留原番号抓取

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
只有这个系列有这种情况么

**Comment by moenimei** [comment]
我这里暂时只碰到这个系列，但想了一下getchu的同人作品应该都有这问题
dl版的下载下来是getchu-xxx的就能正常刮削
但是像这种个人发行的碟片貌似会有番号，用番号在dl那边也无法对应起来，我是直接搜的title才找到的

**Comment by Yuukiy** [comment]
> 我这里暂时只碰到这个系列，但想了一下getchu的同人作品应该都有这问题 dl版的下载下来是getchu-xxx的就能正常刮削 但是像这种个人发行的碟片貌似会有番号，用番号在dl那边也无法对应起来，我是直接搜的title才找到的

这种情况我比较倾向于是卖家自己为自己的作品做了编号并放置在标题中，而不是一个通用的番号。特别是卖家的Twitter用户名是 **t**uba**no**mio**z**isan

**Comment by moenimei** [comment]
> > 我这里暂时只碰到这个系列，但想了一下getchu的同人作品应该都有这问题 dl版的下载下来是getchu-xxx的就能正常刮削 但是像这种个人发行的碟片貌似会有番号，用番号在dl那边也无法对应起来，我是直接搜的title才找到的
> 
> 这种情况我比较倾向于是卖家自己为自己的作品做了编号并放置在标题中，而不是一个通用的番号。特别是卖家的Twitter用户名是 **t**uba**no**mio**z**isan

是这样的，毕竟是同人作品，都是个人拍摄再贩售的，等于他自己定了一个番号，不是正规厂商出品的作品
像sexfriend cmpfans cosぱこ这种也是，番号也没，只能根据他自己的编号去找对应的FC2番号。。。
