### ISSUE TITLE
支持strm文件

### ISSUE THREAD

**Issue by udndhej** [Yuukiy/JavSP#223]
### 功能建议

请问可以支持搜刮strm文件吗，emby和jellyfin都是可以支持播放strm文件的，但是目前好像还不支持搜刮

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
@udndhej 添加了。在新版本释放前，你可以修改你的配置文件里的下面这段来实现对strm的支持
```ini
## 哪些后缀的文件应当视为影片？
media_ext = 3gp;avi;f4v;flv;iso;m2ts;m4v;mkv;mov;mp4;mpeg;rm;rmvb;ts;vob;webm;wmv;strm
```
