### ISSUE TITLE
导入Jvedio后Jvedio无法识别nfo文件

### ISSUE THREAD

**Issue by Juwei-ZHU** [Yuukiy/JavSP#229]
### 问题详情

使用Jvedio的5.4版本（链接：https://github.com/hitchao/Jvedio）
已经在设置中勾选了同时导入扫描出的nfo文件。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by TENTLONG** [comment]
这是你Jvedio设置没设置好，需要调整设置内nfo信息

**Comment by Yuukiy** [comment]
JavSP遵守Kodi对于NFO格式的规范 https://kodi.wiki/view/NFO_files/Movies 该规范也同时被Jellyfin、Emby、Plex等多个媒体软件支持。
根据此规范，`id`是不能使用的字段名，相应地JavSP也按照规范使用的是`uniqueid`
> id
> The default ID.
> Do not use. This is a Kodi generated tag. See next item.
