### ISSUE TITLE
是否考虑增加对anidb的刮削

### ISSUE THREAD

**Issue by lvsaber01** [Yuukiy/JavSP#230]
### 功能建议

可以扩展功能支持对于里番的刮削和识别。anidb上里番数据比较齐全，是否可以增加

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
建议寻找常规刮削器，anidb并没有类似AV番号这样的唯一ID可以用来识别影片。
