### ISSUE TITLE
当演未查询到头像时系统会报错

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#232]
### 问题详情

https://github.com/Yuukiy/JavSP/blob/f12f5a96894231e9b350862a4e56c0cc165f05ea/JavSP.py#L250-L254

这段代码没有考虑到actress_pics 或者actress为None的情况，已提交PR https://github.com/Yuukiy/JavSP/pull/231

### 运行方式

我是从源代码运行的

### 代理

是

### 日志

（fixed)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
Fixed in #231
