### ISSUE TITLE
判断如果有字幕或者文件名有-C的话，封面增加字幕水印

### ISSUE THREAD

**Issue by Yafeiml** [Yuukiy/JavSP#235]
### 功能建议

![poster](https://github.com/Yuukiy/JavSP/assets/16131095/bcbc0e46-9cd0-4aed-843d-a0109490b9cb)
like this

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
https://github.com/Yuukiy/JavSP/issues/73
