### ISSUE TITLE
v1.7.2新版本安装时360报木马病毒，exe文件被360直接删除。

### ISSUE THREAD

**Issue by sbtkggsse** [Yuukiy/JavSP#236]
### 问题详情

开发者你好！
v1.7.2新版本安装时360报木马病毒，exe文件被360直接删除。
ps：我记得之前的老版本不会报毒，请问是哪里有问题吗？
谢谢~~

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
我能想到的风险项只有读取Chrome的cookies，但是这个功能是一直有的。向360请求免杀不在考虑范围内，如果你需要使用的话可以考虑安装python然后以源代码方式运行

**Comment by sbtkggsse** [comment]
感谢回复，再次换电脑和系统测试，确认1.7版本正常（未报毒），1.7.1和1.7.2有这个问题。
谢谢~~

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月4日(周一) 晚上7:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yuukiy/JavSP] v1.7.2新版本安装时360报木马病毒，exe文件被360直接删除。 (Issue #236)




 
我能想到的风险项只有读取Chrome的cookies，但是这个功能是一直有的。向360请求免杀不在考虑范围内，如果你需要使用的话可以考虑安装python然后以源代码方式运行
