### ISSUE TITLE
未知女优也把<actor>tag加入

### ISSUE THREAD

**Issue by delphius81** [Yuukiy/JavSP#238]
### 功能建议

很多素人片可能找不到名字，但建议把未知女优的.nfo里面也加入<actor>tag，可以是空白，方便自行搜寻网站把女优名字填进去保存。

  <actor>
    <name></name>
  </actor>

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你可以创建一个fork版本，然后修改下面代码里写入nfo时的行为
https://github.com/Yuukiy/JavSP/blob/2d439a962a1fffe49c3eefc559d395b7c2928a2e/core/nfo.py#L92
