### ISSUE TITLE
[feature] 希望作者提供命令行版本，我可以提供免费测试环境即远程服务器

### ISSUE THREAD

**Issue by fanza1** [Yuukiy/JavSP#24]
**功能描述**
希望开源社区刮削软件在linux下能有javsdt、avdc-cli之外的选择。

**方案建议**
我可以提供自用的VPS做测试服务器，测试样本可以用javsdt的。我认为python的项目算是移植性非常好的，需要改的地方应该不多。请作者考虑一下。

**Comment by Yuukiy** [comment]
服务器其实不是主要问题，目前没有做Linux版本的主要原因有几个，有一些原因是最近加班比较多，另外其实现在用户很少（按github的数据，1.0版本目前总下载次数72）。而且还有一些预想中的功能（比如AI识别进行封面裁剪）还没做，所以Linux被放到后面去了

**Comment by fanza1** [comment]
AI封面剪裁应该是比较独特的功能，可以理解，那还是新功能优先吧。

**Comment by glyh** [comment]
这个软件已经可以在Linux下跑了，直接手动安装依赖然后python调用JavSP.py就可以了。个人体感比其他的几个代替脚本好用。

**Comment by glyh** [comment]
如果作者需要的话我可以帮忙提供一个pyproject.toml来辅助linux下打包
