### ISSUE TITLE
偶尔会遇到整理出错

### ISSUE THREAD

**Issue by LuiYang08** [Yuukiy/JavSP#242]
### 问题详情

![QQ截图20240310150254](https://github.com/Yuukiy/JavSP/assets/69292505/998c8e72-dd80-4f6e-bd02-9a613a8190f5)

### 运行方式

我是从源代码运行的

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/14549247/JavSP.log)

### 运行截图（可选）

![QQ截图20240310150425](https://github.com/Yuukiy/JavSP/assets/69292505/96689ea8-67bd-4a2e-806a-1bf46f0f102a)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
只支持整理带有番号的影片，不支持常规电影 (`[AI-Raws] Cryingフリーマン #01 杀手肖像 (BD HEVC 1440x1080 FLAC／AC3 英語字幕)[6AA3336A].mkv`这类的)
