### ISSUE TITLE
Patch Mode

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#243]
### 功能建议

有时侯需要在输出目录里运行脚本然后在原地增量更新nfo/翻译元信息,因此我觉得可以增加一个Patch Mode

和 https://github.com/Yuukiy/JavSP/discussions/197  基本一致。
因为这个功能比较常用所以如果有一个快捷的命令来调用而不是修改配置文件的话会比较方便。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
如果觉得有必要的话我可以PR

**Comment by qicfan** [comment]
其实可以做成类似TMM的处理方式，刮削一个功能，重命名/整理一个功能，这样扩展性更强一些。
刮削和整理可以增加命令行参数来区分
刮削可以传入文件路径来刮削指定影片，也可以不加参数刮削整个目录，这样如果有人想做GUI，可以很方便的通过shell调用刮削器。

**Comment by glyh** [comment]
TMM是啥

**Comment by qicfan** [comment]
> TMM是啥

TinyMediaManager，一个通用的刮削器和媒体管理器，如图
![微信图片_20240317140619](https://github.com/Yuukiy/JavSP/assets/758655/56cbc950-c179-4e43-bc7b-e02e602eacf4)

**Comment by Yuukiy** [comment]
https://github.com/Yuukiy/JavSP/issues/249#issuecomment-1991513155

欢迎PR。这个issue我就先关闭了，不然一直在待办事项里
