### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#249]
### 功能建议

有时候可能需要用户输入来决定一些操作，比如多个电影冲突时让用户选择一个

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
所以可以PR吗

**Comment by Yuukiy** [comment]
@glyh 无论何时PR都是非常欢迎的，特别是这种改进易用性的功能。但是如果这个功能会导致停下来等待用户输入，请在配置文件中设置默认状态为关闭或者需要通过特别的命令行参数来开启，否则会导致程序挂起，不利于定期运行、自动任务、Action里的测试用例执行。
