### ISSUE TITLE
希望加入刮削NFO文件信息时可以不要刮削 导演Director 选项。

### ISSUE THREAD

**Issue by Nicotine-2** [Yuukiy/JavSP#253]
### 功能建议

希望加入刮削NFO文件信息时可以不要刮削 导演Director 选项。
如果刮削 Director 信息，在Plex里会在女优头像旁边显示空白的导演头像，影响美观。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你可以fork之后注释掉下面两行
https://github.com/Yuukiy/JavSP/blob/99c1e3ca5c0175b11e981e296861088f0a60d017/core/nfo.py#L74-L75
