### ISSUE TITLE
标题翻译希望能接入能够本地运行的AI模型

### ISSUE THREAD

**Issue by Nemozxy** [Yuukiy/JavSP#255]
### 功能建议

主要是希望接入这个项目：
https://huggingface.co/sakuraumi/Sakura-13B-Galgame
用以提供更适合的翻译

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
炼丹对我来说果然还是太难了
