### ISSUE TITLE
检测到木马程序

### ISSUE THREAD

**Issue by lfeng35** [Yuukiy/JavSP#259]
### 功能建议

检测到病毒是咋回事啊？
Trojan:Win32/Bearfoos.A!ml

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
Dup #236
我能想到的风险项只有读取Chrome的cookies，但是这个功能是一直有的。向360请求免杀不在考虑范围内，如果你需要使用的话可以考虑安装python然后以源代码方式运行
