### ISSUE TITLE
[crawler] 影片DSVR1038数据抓取异常

### ISSUE THREAD

**Issue by Losalkki** [Yuukiy/JavSP#26]
**番号**
DSVR1038-cd1.mp4

**异常数据信息**
不挂代理时可以正确抓取演员名
挂代理时反而不能抓取
建议排查，建议考虑合并字段

**是否使用代理**
挂代理反而出现问题

**Comment by Yuukiy** [comment]
这部影片用的是```normal```里配的抓取器，我看了一下，这些抓取器里只有JavDB有演员数据，挂代理可能触发了JavDB的反爬虫措施，所以导致抓取失败。遇到类似情况可以换个代理地址，或者等一段时间再试试

**Comment by Losalkki** [comment]
OK，Thanks。
