### ISSUE TITLE
“字幕”“无码”图标没有添加到封面图片上

### ISSUE THREAD

**Issue by KarLester** [Yuukiy/JavSP#262]
### 问题详情

首先非常感谢作者提供的这个小程序，我把之前用另一个程序搜刮的影片又重新整理了一遍，效率很高，唯一有的问题就是在Jellyfin里能看到影片的标签上是有对应的标签，但是所有的封面图片都没有“字幕”“无码”图标。我反复阅读过#73 issue的内容，但是就是无法解决这个问题。不知道这个是新的bug，还是我个人使用上的问题。

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by jhonyuan** [comment]
我也是如此，ini文件中也没有相关指引信息，73楼的解释也看不懂。

**Comment by Yuukiy** [comment]
@KarLester @jhonyuan #173 尝试添加了在封面添加图标的功能，但是合并以后会导致一运行就报错，所以后来撤销了； #252 增加了在内嵌字幕的影片添加图标的功能，但是新版本还没有发布，所以从Release界面下载到的应该还不带这个功能。
如果想要尝试的话，可以去Actions里下载小版本 https://github.com/Yuukiy/JavSP/actions/runs/8296310151

**Comment by jhonyuan** [comment]
> @KarLester @jhonyuan #171 尝试添加了在封面添加图标的功能，但是合并以后会导致一运行就报错，所以后来撤销了； #252 增加了在内嵌字幕的影片添加图标的功能，但是新版本还没有发布，所以从Release界面下载到的应该还不带这个功能。 如果想要尝试的话，可以去Actions里下载小版本 https://github.com/Yuukiy/JavSP/actions/runs/8296310151

感谢回复，期待新版本加入该功能，小版本体积太大了，没有梯子21m的压缩包下了两天才完整的下载下来😂

**Comment by Yuukiy** [comment]
@jhonyuan Emm……看起来是那个版本没有把png打包进去，那这个功能目前还是不可用状态。最近几个版本打出来的exe太大，还没有时间处理，所以一直没有释放新版本。你要是急用的话可以试试安装python然后从源代码运行

**Comment by KarLester** [comment]
> @KarLester @jhonyuan #171 尝试添加了在封面添加图标的功能，但是合并以后会导致一运行就报错，所以后来撤销了； #252 增加了在内嵌字幕的影片添加图标的功能，但是新版本还没有发布，所以从Release界面下载到的应该还不带这个功能。 如果想要尝试的话，可以去Actions里下载小版本 https://github.com/Yuukiy/JavSP/actions/runs/8296310151

谢谢回复！我就等更新后的版本好了

**Comment by jhonyuan** [comment]
@Yuukiy 

> @jhonyuan Emm……看起来是那个版本没有把png打包进去，那这个功能目前还是不可用状态。最近几个版本打出来的exe太大，还没有时间处理，所以一直没有释放新版本。你要是急用的话可以试试安装python然后从源代码运行

尝试了安装python，CODE了全部文件，使用idle运行各种报错，可以在目录里加个bat启动器吗，研究好久实在没搞懂，谢谢，另外添加水印的image文件里只看了一个字幕的sub_mark.png，没有无码和破解，期望添加，再次感谢您的回复。

**Comment by qicfan** [comment]
win10或者11的话，用管理员模式打开cmd.exe，然后

> @Yuukiy
> 
> > @jhonyuan Emm……看起来是那个版本没有把png打包进去，那这个功能目前还是不可用状态。最近几个版本打出来的exe太大，还没有时间处理，所以一直没有释放新版本。你要是急用的话可以试试安装python然后从源代码运行
> 
> 尝试了安装python，CODE了全部文件，使用idle运行各种报错，可以在目录里加个bat启动器吗，研究好久实在没搞懂，谢谢，另外添加水印的image文件里只看了一个字幕的sub_mark.png，没有无码和破解，期望添加，再次感谢您的回复。

在项目根目录下面新建个文本文件，然后改名setup.bat，然后把下面一行写到文件里，然后右键->管理员身份打开，这个是配置环境用的：
```
pip install -r .\requirements.txt
```
等上面那个跑完以后，再新建个run.bat，把下面一行写到文件里，直接打开就行：
```
python .\JavSP.py
```

你报错估计是没装好依赖包，我的win11安装依赖必须在管理员模式下，否则就会报错。

**Comment by jhonyuan** [comment]
@qicfan 感谢您的解答，我犯了很多错误，第一个就是未设置环境变量，第二个就是没有pip install -r .\requirements.txt，小白第一天入门，按照您的提示已经成功运行了，再次感谢。

**Comment by glyh** [comment]
似乎已经被修好了
