### ISSUE TITLE
-cd* 分集机制可能出错？识别成了-c，似乎还覆盖了文件，，，，

### ISSUE THREAD

**Issue by Phachd** [Yuukiy/JavSP#268]
### 问题详情

当文件名后缀为xxxxxcd1，xxxxxxcd2时（没有-cd*时）会识别成-c，似乎还会覆盖之前的文件
![7Y71@Q9``T4}L5L1RANR44R](https://github.com/Yuukiy/JavSP/assets/113959688/26e0466d-ca06-4aab-b50c-eb917ba07193)

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Dunky-Z** [comment]
看你的截图并不是-cd而是番号后跟了cd，程序的匹配机制是以-cd匹配，你缺少了`-`短横线。

**Comment by Phachd** [comment]
> 看你的截图并不是-cd而是番号后跟了cd，程序的匹配机制是以-cd匹配，你缺少了`-`短横线。

感谢大佬回复并神速修复。我是确实是没有进行文件名称的处理。这个文件一开始就算没有`-`短横线的哈哈哈哈，这是我的问题。
新版本已经用上了，非常好用。
其实在这两个之外我还观测到一个细节上的逻辑小缺憾。就是我现在的环境是，我下载的视频是先存在一个文件夹，然后我会随机分配进行h265压缩，再把压缩后的视频文件使用您的项目进行元数据处理。
这样我的话会出现有多个分集的，可能不会在一次刮削里面出现。

_**当仅有一个 -cd1 的文件时，似乎会忽略这个-cd1标签**_
![image](https://github.com/Yuukiy/JavSP/assets/113959688/b8f38913-a3e5-4dd0-9e5b-35d7048a76b3)

当缺失-cd1文件时，程序会保留这几个文件不处理（这个逻辑可能是您按此设计的，但上面那个我不确定是不是）
我不知道元数据是不是对分集是有特殊标识的地方的。如果没有的话，应该能够直接将-cd1或者其他-cd*直接丢进这个文件夹，我也不知道什么方法是最好的哈哈哈哈，这应该算是一个小小的改进提议，还是优先级非常低的那种。

彩蛋：
![image](https://github.com/Yuukiy/JavSP/assets/113959688/46285645-deda-4437-92f0-3a9233417be3)
当且仅当有一个.part1标签也不会自动添加-cd1标签。这个是_**不用修改**_的，主要是文件名的可能性太多，规则很难覆盖全部。您隔壁收费的项目是需要按照他们的命名规则的，这个其实开发起来更简单一点哈哈哈哈哈。


最后，感谢您对此项目做出的无私贡献。

**Comment by Yuukiy** [comment]
> 当缺失-cd1文件时，程序会保留这几个文件不处理（这个逻辑可能是您按此设计的，但上面那个我不确定是不是）
> 我不知道元数据是不是对分集是有特殊标识的地方的。如果没有的话，应该能够直接将-cd1或者其他-cd*直接丢进这个文件夹，我也不知道什么方法是最好的哈哈哈哈，这应该算是一个小小的改进提议，还是优先级非常低的那种。

没理解你的意思。
分片的识别是这样的，如果在一次运行中，检测到多个视频文件，具有相同的番号，并且具有除了编号以外非常相似的文件名，且编号连续，那这些视频将被视为同一影片的分片。如果只有一个`cd1`或者`part1`或者是别的类似内容，这部分文本会被忽略（被当做番号识别时的多余信息）。这个过程必须要有多个视频文件才会触发，因为难以从单一文件的文件名里提取编号（可能是cd1, part1, disk1, 第1, 1/4……难以完全覆盖）。使用多个视频文件的话，就非常灵活了，比如这样也没问题
```
IPX-177 part也好cd也好网站的广告也ok随便什么吧1.mp4
IPX-177 part也好cd也好网站的广告也ok随便什么吧2.mp4
```
你的使用场景下，建议压缩完一部影片的全部分片以后再运行整理。

**Comment by Phachd** [comment]
早上好呀。唔，我仔细思考了一下，在这里我可能犯了一个思维定势的错误。是我应该适应您这边的逻辑而不是依照之前使用的同类软件的习惯来提起什么。

这是因为我在之前使用的同类项目。他们指定只识别一种分级后缀（-cd*），这个是需要用户手动重命名的。而且因为他们的逻辑，即使有分集，每个分集文件都会独自处理一遍（所以即使分集在一次处理中不全部，也能进行处理）就好像，他们实现了”添加分集“的功能。但是他们指定的只识别-cd*，所以实现起来简单。

您的项目明显更智能，或者说是花了大力气去维护一个文件名字符串处理模块，这是很厉害的一点。减去了用户处理文件名的繁杂操作。

而我的思维定势让我觉得-cd*（仅仅是-cd*）是一个类似于行业规范的东西，不应该被忽略哈哈哈哈哈哈，但确实是我应该去适应您这边的程序逻辑而不是依照之前的软件习惯或是其他什么hhhhh

接下来我会把不完全的分集放进忽略文件夹，直到他们都存在了再移动出来处理hhhh
感谢您的回复！
________________________________
发件人: Yuukiy ***@***.***>
发送时间: 2024年4月5日 22:59
收件人: Yuukiy/JavSP ***@***.***>
抄送: Phachd ***@***.***>; Mention ***@***.***>
主题: Re: [Yuukiy/JavSP] -cd* 分集机制可能出错？识别成了-c，似乎还覆盖了文件，，，， (Issue #268)


当缺失-cd1文件时，程序会保留这几个文件不处理（这个逻辑可能是您按此设计的，但上面那个我不确定是不是）
我不知道元数据是不是对分集是有特殊标识的地方的。如果没有的话，应该能够直接将-cd1或者其他-cd*直接丢进这个文件夹，我也不知道什么方法是最好的哈哈哈哈，这应该算是一个小小的改进提议，还是优先级非常低的那种。

@Phachd<https://github.com/Phachd> 没理解你的意思。
分片的识别是这样的，如果在一次运行中，检测到多个视频文件，具有相同的番号，并且具有除了编号以外非常相似的文件名，且编号连续，那这些视频将被视为同一影片的分片。如果只有一个cd1或者part1或者是别的类似内容，这部分文本会被忽略（被当做番号识别时的多余信息）。这个过程必须要有多个视频文件才会触发，因为难以从单一文件的文件名里提取编号（可能是cd1, part1, disk1, 第1, 1/4……难以完全覆盖）。使用多个视频文件的话，就非常灵活了，比如这样也没问题

IPX-177 part也好cd也好网站的广告也ok随便什么吧1.mp4
IPX-177 part也好cd也好网站的广告也ok随便什么吧2.mp4


你的使用场景下，建议压缩完一部影片的全部分片以后再运行整理。

―
