### ISSUE TITLE
在JAVDB抓取FC2影片时，JAVDB没有演员信息等必须项会导致抓取失败

### ISSUE THREAD

**Issue by ACCOUNT-UNKNOWN** [Yuukiy/JavSP#27]
**bug详情**
描述这个bug的出现场景、现象等

**如何复现**
经过怎样的操作过程发现了这个bug
如果这个问题可能和配置文件相关，请附上你的配置

**截图**
提供屏幕截图（注意对必要信息打码）

**Comment by Yuukiy** [comment]
可以从配置里去掉```required_keys = cover,genre,title,actress```中的```actress```
