### ISSUE TITLE
windows下无法获取cookie

### ISSUE THREAD

**Issue by 972782297** [Yuukiy/JavSP#271]
### 问题详情

报错“AESGCM key must be 128, 192, or 256 bits.”，似乎是因为解密算法不对导致的
简单看了下[chromium源码](https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/sync/os_crypt_win.cc;bpv=0;bpt=1)，在windows环境下Local State中的key依然是用dpapi加密的，所以是不是我们应该依然用dpapi来解密，而非用AESGCM？

![image](https://github.com/Yuukiy/JavSP/assets/45987161/3a188b03-9045-4896-828e-ad822e68ed15)

### 运行方式

我是从源代码运行的

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by glyh** [comment]
在很多github workflow的failing log里都有复现，比如：https://github.com/Yuukiy/JavSP/actions/runs/8713950780?pr=284

**Comment by Yuukiy** [comment]
0c1024d75a19ab8fbfd5058ba479a91a97a77fb9 引入的，覆盖掉了原来的解密函数，导致Windows下解析不了cookie
