### ISSUE TITLE
获取JavDB的登录凭据时出错

### ISSUE THREAD

**Issue by sevinyim** [Yuukiy/JavSP#273]
### 问题详情

bug目前仅发生于**部分**fc2影片上，其他影片可以正常获取信息
出现bug的影片文件名：
>FC2-1717523-1
FC2-1717523-2
FC2-1723082-1
FC2-1723082-2
FC2-2278841-1
FC2-2278841-2

错误信息如下：
>获取JavDB的登录凭据时出错(AESGCM key must be 128, 192, or 256 bits.)，你可能使用的是国内定制版等非官方Chrome系浏览器
命名规则导致标题被截断至空，请增大'max_path_len'或减小'max_actress_count'配置项后重试
整理失败: 无法按命名规则生成目标文件夹

***已经尝试了在配置文件中修改两项参数，依然报错***
浏览器为Chromium内核的Edge（Windows 11），可以正常登录JAVDB（非会员）

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/14935232/JavSP.log)

### 运行截图（可选）

<img width="919" alt="image" src="https://github.com/Yuukiy/JavSP/assets/8608459/57b98bcf-a2c5-4eda-a3bc-7cc2071af0bc">

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by yanwuhuo1** [comment]
你怎么解决的？
