### ISSUE TITLE
希望能增加演员图片刮削功能，演员图片javdb网站比较全，可以作为主要资源对象

### ISSUE THREAD

**Issue by gejianya** [Yuukiy/JavSP#275]
### 功能建议

如题，刮削下来的演员图片希望跟nfo文件放在同一个文件夹内，同时建立名为.actors文件夹，将图片放入此文件夹，同时图片名称为演员名.jpg，这样emby可以完美识别并加载演员图片，谢谢。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
在能够直接从影片页面获得女优头像时，nfo会生成对应的URL，比如javbus。
```xml
  <actor>
    <name>あず希</name>
    <thumb>https://www.javbus.com/pics/actress/pvp_a.jpg</thumb>
  </actor>
```

   但不是所有网站都会直接提供头像。如果你想要全女优头像，建议使用 https://github.com/gfriends/gfriends

https://github.com/Yuukiy/JavSP/issues/183#issuecomment-1872653801
