### ISSUE TITLE
[bug] 在标题过长时出现一个整理失败的bug

### ISSUE THREAD

**Issue by Losalkki** [Yuukiy/JavSP#29]
bug详情
（我习惯在文件夹和文件名中包含标题）
当标题过长时会发生创建文件失败的BUG

如何复现
在配置中修改
```
save_dir = $num[$actress]$rawtitle
filename = $num[$actress]$rawtitle
```

整理IPVR150（原标题长达116个字）

Windows似乎限制路径长度为127.5个全角字符，在因此建议设置两个阈值，供人截断文件夹名和文件名。

**Comment by Yuukiy** [comment]
在我看来类似的阈值应该由软件处理，用户去学习和关注系统机制也是需要精力的，应该尽量减少这种情况。
这个问题是由于路径长度限制机制没有作用到```$rawtitile```上导致的，已修复，可到 https://github.com/Yuukiy/JavSP/actions/runs/1616045677 下载临时版使用。

**Comment by Losalkki** [comment]
> 在我看来类似的阈值应该由软件处理，用户去学习和关注系统机制也是需要精力的，应该尽量减少这种情况。 这个问题是由于路径长度限制机制没有作用到`$rawtitile`上导致的，已修复，可到 https://github.com/Yuukiy/JavSP/actions/runs/1616045677 下载临时版使用。

GREAT！但是这样的话似乎还是会导致未来移动到更长路径的文件夹时候有可能造成隐患。

**Comment by Yuukiy** [comment]
> > 在我看来类似的阈值应该由软件处理，用户去学习和关注系统机制也是需要精力的，应该尽量减少这种情况。 这个问题是由于路径长度限制机制没有作用到`$rawtitile`上导致的，已修复，可到 https://github.com/Yuukiy/JavSP/actions/runs/1616045677 下载临时版使用。
> 
> GREAT！但是这样的话似乎还是会导致未来移动到更长路径的文件夹时候有可能造成隐患。

你要是有这样的需求，可以现在把整理目录的名字放得长一点或者深一点

**Comment by Losalkki** [comment]
> 
好办法！
