### ISSUE TITLE
用cx_Freeze代替pyinstaller

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#290]
### 功能建议

pyinstaller太慢了，cx_Freeze在[这里](https://github.com/marcelotduarte/cx_Freeze)。唯一缺陷就是之后不再是一个单独的二进制文件，而是一个文件夹。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
非单一文件在release和自动更新上难以处理，暂不考虑
