### ISSUE TITLE
打开 exe 程序报错

### ISSUE THREAD

**Issue by vvandk** [Yuukiy/JavSP#295]
### 问题详情

直接打开 exe 程序报错

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

无

### 运行截图（可选）

![image](https://github.com/Yuukiy/JavSP/assets/108704266/c3ff3eda-c0a4-4a29-96b4-c23b862fdd92)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by glyh** [comment]
这个issue似乎是我的fork的而不是yuukiy维护的分支的bug，请在https://github.com/glyh/JavSPn/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc 反馈

**Comment by glyh** [comment]
https://github.com/marcelotduarte/cx_Freeze/issues/1288

**Comment by glyh** [comment]
请在控制台打开程序

**Comment by vvandk** [comment]
不好意思，确实提交错地方了，打扰了。我会尝试使用 https://github.com/glyh/JavSPn/actions/runs/8801411907 该包，感谢回答
