### ISSUE TITLE
这是简介太长了吗

### ISSUE THREAD

**Issue by Yangrixiao** [Yuukiy/JavSP#3]
------------------------------------------------------------------------------------------------------------------------
JavSP.py 272 <module>
"D:\soft\JavSP-master\JavSP.py", line 272
write_nfo(movie.info, movie.nfo_file)

nfo.py 34 write_nfo
"D:\soft\JavSP-master\core\nfo.py", line 34
nfo.append(E.plot(info.plot))

builder.py 226 lxml.builder.ElementMaker.__call__
"src\lxml\builder.py", line 226

TypeError:
bad argument type: list(['白く綺麗な柔肌を真っ赤な縄と首輪で強制固定！カラダを縛られ身動きの取れない美女にバイブを固定し首を絞めていく。苦しい…アッ‥気持ちぃ…！不安と緊張の表情が徐々に恍惚の表情へと変わっていく…。調教された彼女は貴方だけのペットとしてねっとりと濃厚なフェラチオにイラマチオ、パイズリなど奉仕の限りを尽くす。※こちらの作品はCasanovA開発の超精細カメラで撮影、HQハイクオリティ版（高画質・60fpsの滑らかな動きを実現）に対応、バイノーラル録音されています。'])

**Comment by Yuukiy** [comment]
你是从仓库里最新状态的代码运行的是么？ 这个问题只在代码状态的项目里有，已修复： 518d495

**Comment by Yangrixiao** [comment]
是的 我是linux 直接运行源码 感谢大佬
