### ISSUE TITLE
[bug] 在刮取时出现一个所有爬虫均未获取到字段: 'cover'的bug

### ISSUE THREAD

**Issue by wqh131311** [Yuukiy/JavSP#30]
默认配置出现这个情况，使用了代理

**Comment by wqh131311** [comment]
check_hostname requires server_hostname
check_hostname requires server_hostname
check_hostname requires server_hostname
check_hostname requires server_hostname
check_hostname requires server_hostname
check_hostname requires server_hostname
所有爬虫均未获取到字段: 'cover'，抓取失败
整理失败:

**Comment by wqh131311** [comment]
设置中的网站均可以用代理登陆

**Comment by Yuukiy** [comment]
**如果是整理某部特定影片时出现的问题，必须附上影片番号**

**Comment by Yuukiy** [comment]
无后续反馈
