### ISSUE TITLE
希望可以通过文件名来进行刮削

### ISSUE THREAD

**Issue by Julyxunle** [Yuukiy/JavSP#300]
### 功能建议

这个提议是针对一些里番，通常从字幕组下载的里番都不是以id的方式存放的，希望可以通过扫描文件名的方式来进行刮削，文件名可以通过正则等方式来忽略部分片段来达到精准刮削的目的
例如片名“[230127][ピンクパイナップル]スリーピース THE ANIMATION.chs”可以在fanza中搜索“スリーピース THE ANIMATION”这一部分来获取到影片信息

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
建议是可行的，但是实施起来比较困难。
文件名不一定规范导致的结果不准确
日本搜索带来的结果不可预测导致不符合预期

只是里番的话其实有人做过历年的数据合集，里面已经包括了刮削数据。
https://sukebei.nyaa.si/view/3828554
https://sukebei.nyaa.si/view/4061896

**Comment by Julyxunle** [comment]
> 建议是可行的，但是实施起来比较困难。 文件名不一定规范导致的结果不准确 日本搜索带来的结果不可预测导致不符合预期
> 
> 只是里番的话其实有人做过历年的数据合集，里面已经包括了刮削数据。 https://sukebei.nyaa.si/view/3828554 https://sukebei.nyaa.si/view/4061896

感谢大佬给的链接，这个项目可以帮我解决大部分里番的整理目的了，剩下小部分不包含的我可以通过手动搜索cid的方式来刮削

另外，针对您说的两个问题，确实是存在的，包括同一个名称可能搜索出多个结果，难以保证准确性，但我仍然希望可以通过剧集名称进行刮削（作为一个可选的功能）。
