### ISSUE TITLE
希望可以添加演员图片的下载

### ISSUE THREAD

**Issue by bginan** [Yuukiy/JavSP#304]
### 功能建议

开发者您好，非常感谢您开发这么棒的软件，用得非常开心，希望能考虑添加下载演员照片的功能，再次感谢！

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
这个功能已经实现了，但是有些站点是不支持的，你获取的数据可能不同。
https://github.com/Yuukiy/JavSP/blob/master/core/nfo.py#L95

**Comment by Yuukiy** [comment]
https://github.com/Yuukiy/JavSP/issues/275#issuecomment-2056628515
https://github.com/Yuukiy/JavSP/issues/183#issuecomment-1872653801
