### ISSUE TITLE
无法绕开JavLib的反爬机制

### ISSUE THREAD

**Issue by generaljun** [Yuukiy/JavSP#306]
### 问题详情

==============================================
   Jav Scraper Package: v1.7.3 (已是最新版)
==============================================

请选择要整理的文件夹：Z:\media\javSp
扫描影片文件...
扫描影片文件：共找到 2 部影片

正在整理: 1037933-C.mp4
无法绕开JavLib的反爬机制
整理失败: 为其配置的8个抓取器均未获取到影片信息

正在整理: hhd800.com@FC2-PPV-2848093.mp4
fc2fan: 站点不可用
fc2fan: 站点不可用
fc2fan: 站点不可用
整理失败: 为其配置的5个抓取器均未获取到影片信息

请按任意键继续. . .

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 运行截图（可选）

![微信图片_20240518032429](https://github.com/Yuukiy/JavSP/assets/37947969/9a2c9b52-d11f-46bb-9d62-a957809eed98)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
文件命名不规范，看起来像是fc2的视频，可以尝试改名为fc2-ppv-1037933.mp4

**Comment by generaljun** [comment]
> 文件命名不规范，看起来像是fc2的视频，可以尝试改名为fc2-ppv-1037933.mp4

感谢。已经按照建议重命名，有一个完成了整理，另一个整理失败。正如您分析的，这种命名错误，会导致自动整理失败。
