### ISSUE TITLE
部分仅在月额影片中有的CID无法刮削

### ISSUE THREAD

**Issue by TENTLONG** [Yuukiy/JavSP#307]
### 问题详情

如以下CID，仅使用月额影片选项搜索可搜索出
kntr0002
kntr0005
kntr0006

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
尚不支持
![image](https://github.com/user-attachments/assets/4b1cdfef-f4d5-45c3-b3d2-28ee0e93db48)
