### ISSUE TITLE
[feature] 希望开发针对已在路由器端翻墙无需在本地设置代理的功能

### ISSUE THREAD

**Issue by xmasrain** [Yuukiy/JavSP#31]
![image](https://user-images.githubusercontent.com/58833842/148058000-8843c382-c45c-4e08-9920-e2ecb5337440.png)

我已在路由器端科学上网，这些网站我都能打开，无需配置本地代理，但是如果我此处填no，则限制了部分功能。

**Comment by Yuukiy** [comment]
你可以填```no```，没关系，不影响使用的，不会因为你填```no```了就丢失功能或者禁用某些站点的爬虫，功能上只有一点小小的差异：填```no```的情况下，爬虫会用免代理地址访问网站，如果恰好网站的免代理地址更新了，那可能会爬不到网站。
你可以在配置文件里把那些免代理地址填成相应网站的永久地址，这样的话就没有差异了。

**Comment by Yuukiy** [comment]
这里加这个提示主要是对不使用代理的用户做一个提醒，了解部分站点可能会因为没有代理访问不了而抓取失败，不会主动限制功能的。后面会把这块的提示优化一下

**Comment by smurfs9** [comment]
不知道为什么我已经开了全局，可以正常访问外网，但是一打开软件就说没代理，直接退出了

**Comment by Yuukiy** [comment]
> 不知道为什么我已经开了全局，可以正常访问外网，但是一打开软件就说没代理，直接退出了

软件的代理要单独设置，在配置文件里，建议看一遍配置文件。

**Comment by smurfs9** [comment]
> 

是否启用代理那里设置了 `yes` ,代理端口也跟电脑本地设置的1080一样，但是一启动就弹出命令行界面，飞速地输出几行，就闪退了

**Comment by smurfs9** [comment]
![VeryCapture_20220113145117](https://user-images.githubusercontent.com/53073225/149280963-4dc2b680-08a7-41ae-9523-9ebc151f0846.jpg)
第一次启动后，在生成的`config.ini`文件修改了`use_proxy = yes`，代理`proxy = http://127.0.0.1:1080`，但是打开软件就是弹出图片所示窗口然后闪退。

**Comment by Yuukiy** [comment]
> 

我没有复现这个问题，看报错信息是config.ini解析出错。你上传一下你的config.ini文件？

**Comment by Yuukiy** [comment]
> ![VeryCapture_20220113145117](https://user-images.githubusercontent.com/53073225/149280963-4dc2b680-08a7-41ae-9523-9ebc151f0846.jpg) 第一次启动后，在生成的`config.ini`文件修改了`use_proxy = yes`，代理`proxy = http://127.0.0.1:1080`，但是打开软件就是弹出图片所示窗口然后闪退。

我没有复现这个问题，看报错信息是config.ini解析出错。你上传一下你的config.ini文件？

**Comment by smurfs9** [comment]
[config.zip](https://github.com/Yuukiy/JavSP/files/7889341/config.zip)
配置文件

**Comment by Yuukiy** [comment]
> [config.zip](https://github.com/Yuukiy/JavSP/files/7889341/config.zip) 配置文件

已修复，可以来 https://github.com/Yuukiy/JavSP/actions/runs/1713863882 下载临时版本。
（以为很快就能改完，结果到现在。果然还是不能工作日干这个，希望明天不要迟到😭）

**Comment by smurfs9** [comment]
成功了，感谢修复

**Comment by Yuukiy** [comment]
> 这里加这个提示主要是对不使用代理的用户做一个提醒，了解部分站点可能会因为没有代理访问不了而抓取失败，不会主动限制功能的。后面会把这块的提示优化一下

已于 88fb49da 移除提示
