### ISSUE TITLE
特殊字符与多集刮削问题

### ISSUE THREAD

**Issue by Timk-ztls** [Yuukiy/JavSP#312]
### 问题详情

1  特殊字符会导致创建的文件夹名字不全的问题如下
错误名字：FC2-3691170 【初撮り
正确名字：FC2-3691170 【初撮り♡】 0344_001 みゆちゃん18歳 発育途中の150cm・30kg台色白ボディにGカップ美巨乳の超絶美少∕女LJ◯アイドルが誕生日と同時に無許∕可中出し孕ませAVデビューで人生終了（爆）

2 多集刮削会提示名称错误
当CD数量多余9集后会出现无法刮削的情况 提示名称命名错误被忽略，需要把大于9的集数剪切出来 等刮削完毕后再移回去

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [x] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
命名截断的问题你可以参考下面的内容进行修改，已经提交了pr。
`https://github.com/musnow/JavSP/blob/master/web/msin.py#L82`
多分片超过9个时无法刮削在代码里已经写死，不太好改，你刮削出来emby和plex等软件也不支持的，所以还是别这样弄了
