### ISSUE TITLE
更多影片重命名规则

### ISSUE THREAD

**Issue by 0oFlameo0** [Yuukiy/JavSP#314]
### 功能建议

我希望把我的影片重命名为
$actress_$num_$rawtitle
（演员名字，番号，题目，中间用下划线分隔）
的格式，但是我得到了如下的错误
KeyError: 'actress_'

似乎无法区分关键词和分隔符的区别。
能否考虑提供更多的文件名命名规则。

以及，多个女优名字默认为逗号分隔符，能否增加一个参数自定义分隔符，比如-

最后感谢您开发了如此方便的工具。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
"$actress _ $num _ $rawtitle"，这样子应该可以，空格会自动去除的。

**Comment by musnow** [comment]
> "$actress _ $num _ $rawtitle"，这样子应该可以，空格会自动去除的。

试了一下，上面这种方法不行，需要直接暴露变量。
${actress}_${num}_${rawtitle}

**Comment by Yuukiy** [comment]
感谢 @musnow 测试~之前没有考虑到，我更新到wiki里
