### ISSUE TITLE
请求支持多个文件夹路径

### ISSUE THREAD

**Issue by ggrreeeedd** [Yuukiy/JavSP#318]
### 功能建议

config里面的scan_dir能同时支持多个文件夹吗？一行对应一个文件夹路径

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
可以，但是没必要，多个文件夹可以分多次执行即可。
scan_dir为空时，运行会询问你需要整理的路径，你的场景建议这样操作。

**Comment by ggrreeeedd** [comment]
> 可以，但是没必要，多个文件夹可以分多次执行即可。 scan_dir为空时，运行会询问你需要整理的路径，你的场景建议这样操作。

采集的信息每个站会稍有不同，所以需要单独建立多个文件夹整理，而每次需要更新的时候都需要n次输入文件路径

**Comment by musnow** [comment]
对于多个站点都有的信息，程序会聚合结果合并输出的。
https://github.com/Yuukiy/JavSP/blob/master/JavSP.py#L162

**Comment by ggrreeeedd** [comment]
> 对于多个站点都有的信息，程序会聚合结果合并输出的。 https://github.com/Yuukiy/JavSP/blob/master/JavSP.py#L162

在CrawlerSelect下，设置不同的顺序，结果很大不同，取决于网站的提供的信息，识别和整合还是有混乱，之前有过某月之前信息都正常，而某月之后都归类于#未知，某些站对于古早的番号识别也不同，手动整理还是有需求

**Comment by musnow** [comment]
这是原理使然，CrawlerSelect列表越前拿到数据的优先级越高，比如说两个模块都有标题，但是程序会取第一个模块的数据而不是第二个。
反之，如果第一个模块没有的数据，那就会从前到后全部遍历直至拿到数据，最终合并出来是所有模块数据的并集。
你这个场景也不是需要多工作文件夹，而是不同文件夹设置不同的模块，你可以在你不同文件夹下面复制新的程序和配置文件来进行刮削，从而实现不同的设置。

**Comment by ggrreeeedd** [comment]
> 这是原理使然，CrawlerSelect列表越前拿到数据的优先级越高，比如说两个模块都有标题，但是程序会取第一个模块的数据而不是第二个。 反之，如果第一个模块没有的数据，那就会从前到后全部遍历直至拿到数据，最终合并出来是所有模块数据的并集。 你这个场景也不是需要多工作文件夹，而是不同文件夹设置不同的模块，你可以在你不同文件夹下面复制新的程序和配置文件来进行刮削，从而实现不同的设置。

是的，提出这个请求是也同时想对系统文件夹的进行整理，而不是对元数据
