### ISSUE TITLE
linux平台自动更新支持

### ISSUE THREAD

**Issue by fanwenlin** [Yuukiy/JavSP#320]
### 功能建议

当前自动更新只支持Windows release，在linux下触发自动更新后仍然会下载exe导致运行失败，当前可以禁用自动更新解决
希望后续自动更新可以适配其他平台

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
这是一个bug，如果你很关心更新内容，可以尝试直接拉取项目使用。

**Comment by glyh** [comment]
建议是Linux用户将软件打包到对应平台的包管理器上。已经默认配置下的禁用自动更新https://github.com/Yuukiy/JavSP/commit/ad241781460d18d2354b9ca124e25efddc5bcb56

**Comment by glyh** [comment]
现在CI分别构建三大平台的二进制文件了，如果你还需要这个功能的话欢迎PR：
https://github.com/Yuukiy/JavSP/actions/runs/11065159554
