### ISSUE TITLE
如何彻底取消中文标题翻译？

### ISSUE THREAD

**Issue by RYOTENG** [Yuukiy/JavSP#324]
### 功能建议

如题如何彻底取消中文标题翻译？我只需要日文原文。标题处理：优先使用中文标题（如果能获取到的话）、是否翻译标题、是否翻译剧情简介均设为No，依然会偶尔出现某个影片是中文。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
只需要你在配置文件Translate->engine配置为空即可关闭翻译，偶见中文是有些模块只有中文的信息，你可以查看日志验证。
https://github.com/Yuukiy/JavSP/blob/master/JavSP.py#L492
