### ISSUE TITLE
整理失败: [Errno 63] File name too long

### ISSUE THREAD

**Issue by raighneweng** [Yuukiy/JavSP#326]
### 问题详情

整理时正常运行吗，但重命名失败，提示保存整理失败: [Errno 63] File name too long: 

### 运行方式

我是从源代码运行的

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
字面意思，文件名太长了，应该是你路径太深导致的，默认会截断。

**Comment by raighneweng** [comment]
不是路径太深，路径就在 /Volumes/AV。
应该是文件夹名太长，系统不支持。

`整理失败: [Errno 63] File name too long: '#整理完成/Gカップ純白極上ボディめいちゃん/[FC2-xxxxxxxxx] 【数量限定販売】※特別早期購入者特典有【顔出し】これを超えるものは出てこないと思います。ここまでの美女見たことありますか？あの作品の続きが…多くは語れませんので欲しい人だけ買って下さい'`

**Comment by raighneweng** [comment]
OS: MacOS

**Comment by musnow** [comment]
不应该啊，你把calc_path_len_by_byte设置成no，max_path_len设置到240，然后试试，还不行你上传日志我看看。

**Comment by raighneweng** [comment]
calc_path_len_by_byte从auto设置成yes，max_path_len设置到240成功了
