### ISSUE TITLE
关闭翻译功能后 Javdb依然返回中文标题

### ISSUE THREAD

**Issue by maxwsws1** [Yuukiy/JavSP#328]
### 问题详情

1.在优先使用Javdb的情况下, 6月19日未做任何设置的调整, 突然出现该问题
2.问题表现为但凡Javdb上有中文标题的影片都会返回中文标题, 如NSFS-091,NSFS-105, 而类似NSFS-124这种没有中文标题的, 则正常返回原标题
3.设置文件里相关的几个设置如下, 之前也是这样, 也都是原标题, 今日突然变成返回中文
normal = javdb,javbus
fc2 = javdb,fc2,fc2fan,msin,javmenu
title__chinese_first = no
# 是否翻译标题
translate_title = 
4.试过的排查如下:
    1).怀疑跟缓存有关, 试过尝试访问Javdb网页并登陆后设置网页语言为英文, 问题依然
    2).试过切换不同的VPN地区, 包括繁体语言的地区和英语语言的地区和日本地区, 问题依然
    3).试过不使用代理, 且网址可以正常访问打开的, 问题也是依然

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/user-attachments/files/15890368/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
这个问题同#324
你可以拉取项目，然后将web/javdb.py的140行修改成以下内容可以暂时解决这个问题。
`title = container.xpath("h2/span/text()")[0]`
https://github.com/Yuukiy/JavSP/blob/master/web/javdb.py#L140

**Comment by maxwsws1** [comment]
大神您好!
感谢百忙抽空回复, 由于我没有编程基础, 也没安装python, 拉取项目并修改的部分可能我不会操作, 然后我参考了#324的内容, 我把翻译引擎设置为空暂时问题是依然的, 我先暂时把Javdb更换成bus,待后续版本更新我再重新设置回Javdb, 希望再后续版本中能更新该问题, 感谢感谢.

**Comment by Yuukiy** [comment]
@maxwsws1 把配置文件中的`$title`改成`$rawtitle`
![image](https://github.com/user-attachments/assets/40910ce7-296d-4675-bd0d-ae5e272a9c7f)
效果
![image](https://github.com/user-attachments/assets/0613f62a-36fa-400a-9feb-3f1f120565d9)

文档见 https://github.com/Yuukiy/JavSP/wiki/NamingRule-%7C-%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99
