### ISSUE TITLE
可否不更改原文件标题

### ISSUE THREAD

**Issue by Abibabodudu** [Yuukiy/JavSP#329]
### 功能建议

我的视频文件的标题已经是对的且为中文，能否不更改整理后的文件名称。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
将配置文件的enable_file_move = yes改成no即可不移动文件。

**Comment by mbhyaaa** [comment]
> 将配置文件的enable_file_move = yes改成no即可不移动文件。

配置文件里没有这个选项呀。可以移动文件但是不重命名吗？

**Comment by musnow** [comment]
配置文件config.ini->File->enable_file_move
不可以。

**Comment by htyxyt** [comment]
> > 将配置文件的enable_file_move = yes改成no即可不移动文件。
> 
> 配置文件里没有这个选项呀。可以移动文件但是不重命名吗？

[JavSP-NotRename](https://github.com/htyxyt/JavSP-NotRename)，自己曲线救国了一下，先保存文件名，整理完再改回去。
