### ISSUE TITLE
影片T38-002无法刮削 

### ISSUE THREAD

**Issue by Mr-Chatwin** [Yuukiy/JavSP#332]
### 问题详情

T38-002无法刮削，是TMA制作商的，番号确实比较奇怪

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

2024-06-27 00:26:45 core.file:59 ERROR: 无法提取影片番号: '\\192.168.5.88\nas\hlink\r18\tmdb\T38-002.mp4'
2024-06-27 00:26:45 main:543 ERROR: 未找到影片文件

### 运行截图（可选）

![image](https://github.com/Yuukiy/JavSP/assets/21234158/3b9296f0-c8db-47c3-a80a-b550d328a8c4)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
番号特殊导致的未匹配，鉴于作者蛮久没有更新，可以下去下面的项目运行。
https://github.com/musnow/JavSP/

**Comment by glyh** [comment]
@musnow 我之前有一个fork，修改了一些功能，还在更新，最近有可能继续跟进，有意向和我一起维护吗？

https://github.com/glyh/JavSPn

**Comment by musnow** [comment]
> @musnow 我之前有一个fork，修改了一些功能，还在更新，最近有可能继续跟进，有意向和我一起维护吗？
> 
> https://github.com/glyh/JavSPn

水平有限，只能做些力所能及的事情。
