### ISSUE TITLE
希望可以增加设置修改nfo信息和影片名字相同的功能

### ISSUE THREAD

**Issue by StevesHarrington** [Yuukiy/JavSP#333]
### 功能建议

希望可以增加设置修改nfo信息和影片名字相同的功能，极空间用原nfo无法显示刮削后的内容。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
没看懂你的描述哈，你的意思是nfo文件和媒体文件名同名？
或者是nfo的标题和媒体文件名同名？

**Comment by musnow** [comment]
你可以参考下面的链接自己先测试一下到底是怎么样的支持。
[#163 ](https://github.com/Yuukiy/JavSP/pull/163)

**Comment by jimmymitlavigne** [comment]
我和楼主有一样的需求，我刚刚测试了。当配置文件中的命名规则参数，从(universal)改为jellyfin时，nfo会和媒体会同名，但是nfo识别会出现问题 ，影片的介绍变成了日语，当参数为(universal)时，影片介绍为中文「我手动改成同名测试」。
能否增加一个可选项，当配置规则为(universal)时，可选nfo信息和影片名字相同的功能，比如影片abc-123.mp4，abc-123.nfo

**Comment by musnow** [comment]
配置媒体服务器应该是不会对内容进行更改的，只是刮削模块获取到的内容不同，如果你不确定可以上传日志进行确认

**Comment by jimmymitlavigne** [comment]
那应该是参数为jellyfin时 nfo写入信息的格式不一样，别的都正常，只有影片介绍为日语

**Comment by musnow** [comment]
有番号或者网站吗，我明天测试下

**Comment by jimmymitlavigne** [comment]
比如，JKSR-140 和 NANP-005

**Comment by musnow** [comment]
实际刮削使用的数据源是下面的两个网址，内容均为日文，并未出现你说的不容媒体服务器出现内容不相符的情况，你可能是开启了翻译，你可以上传日志再次确认。
https://www.airav.wiki/video/NANP-005
https://www.airav.wiki/video/JKSR-140

**Comment by Yuukiy** [comment]
issue提出者没有后续反馈，我就先关闭了。感谢 @musnow 测试~
