### ISSUE TITLE
win版本支持刮削演员的图像吗？作者是否考虑添加？

### ISSUE THREAD

**Issue by Ahdjdus** [Yuukiy/JavSP#334]
### 功能建议

我目前为止使用win11进行刮削，之后导入 jellyfin 中。但是影片的演员图像无法获得。我应该做什么才能找到图像添加进去？win版本有这个功能吗？

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
某些网站有演员图像的会采集写入，没有写入的你可以使用以下项目自行导入emby等媒体服务器。
https://github.com/gfriends/gfriends

**Comment by Ahdjdus** [comment]
非常感谢
