### ISSUE TITLE
里番的刮削还是要去GETCHU.COM

### ISSUE THREAD

**Issue by legpuller** [Yuukiy/JavSP#335]
### 功能建议

希望作者能加入GETCHU.COM的网站，刮里番还是得靠它。我试了好多个网站，要不就是片源不全，要不就是一部里番的介绍内容不全。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
同#300
项目支持里番只是某些巧合，应该不会进一步支持，建议参考上面的issues自行操作。
