### ISSUE TITLE
403错误 必须要挂代理才能解决吗  javbus防屏蔽地址不能搜刮吗

### ISSUE THREAD

**Issue by gabriel94yulexing** [Yuukiy/JavSP#339]
### 问题详情

403错误 必须要挂代理才能解决吗  javbus防屏蔽地址不能搜刮吗

### 运行方式

我是从源代码运行的

### 代理

否

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
你可以使用防屏蔽地址，当前不是最新的地址，你可以自行修改。

**Comment by shatangxiaoyan** [comment]
> 你可以使用防屏蔽地址，当前不是最新的地址，你可以自行修改。

如何修改至反屏蔽地址

**Comment by musnow** [comment]
https://github.com/Yuukiy/JavSP/discussions/313
