### ISSUE TITLE
ubuntu18 : ERROR: No matching distribution found for pywin32>=223

### ISSUE THREAD

**Issue by gdcplasf** [Yuukiy/JavSP#34]
python:3.10.2
ubuntu:18

ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223

在ubuntu18下报没有pywin32

**Comment by Yuukiy** [comment]
你在Ubuntu下运行的话应该是跑的代码了，用pywin32是要使用它的加密库，把```web\javdb.py```里的
```python
from core.chromium import get_browsers_cookies
```
去掉就好了

**Comment by gdcplasf** [comment]
OK,谢谢

**Comment by Yuukiy** [comment]
Solved
