### ISSUE TITLE
刮削出来的nfo文件，有两行标签错误

### ISSUE THREAD

**Issue by htyxyt** [Yuukiy/JavSP#341]
### 问题详情
```xml
  <uniqueid type="num" defult="true">SONE-219</uniqueid>
  <uniqueid type="cid">sone00219</uniqueid>
```
这两行标签格式错误，导致视频管理软件无法匹配。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/user-attachments/files/16243726/JavSP.log)
[movie.txt](https://github.com/user-attachments/files/16243743/movie.txt)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
这个是是在kodi规范里面的标签，可能和你匹配的问题不是出在这里，你用的什么软件。
https://kodi.wiki/view/NFO_files/Movies

**Comment by htyxyt** [comment]
> 这个是是在kodi规范里面的标签，可能和你匹配的问题不是出在这里，你用的什么软件。 https://kodi.wiki/view/NFO_files/Movies

用的视频管理软件是这个[Jvedio](https://github.com/hitchao/Jvedio)。
我也用[MDCx](https://github.com/sqzw-x/mdcx)刮削过，它的格式是`<num>SONE-219</num>`这种形式。
我自己把这两行改一下，就能识别了，那应该是兼容问题。

**Comment by musnow** [comment]
这是[Jvedio](https://github.com/hitchao/Jvedio)这个软件不能支持uniqueid标签，你可以去那边提一下，本项目也没有对Jvedio进行测试，如果还遇到什么问题欢迎issues。
临时解决你可以自己修改一些nfo.py从50行到53行的内容为下面这段代码.
```    if info.dvdid:
        nfo.append(E.num(info.dvdid))
    if info.cid:
        nfo.append(E.cid(info.cid))```
https://github.com/Yuukiy/JavSP/blob/master/core/nfo.py#L50

**Comment by htyxyt** [comment]
> 这是[Jvedio](https://github.com/hitchao/Jvedio)这个软件不能支持uniqueid标签，你可以去那边提一下，本项目也没有对Jvedio进行测试，如果还遇到什么问题欢迎issues。 临时解决你可以自己修改一些nfo.py从50行到53行的内容为下面这段代码.
> 
> ```
>         nfo.append(E.num(info.dvdid))
>   if info.cid:
>         nfo.append(E.cid(info.cid))
> ```
> 
> https://github.com/Yuukiy/JavSP/blob/master/core/nfo.py#L50

好的，谢谢
