### ISSUE TITLE
添加对javtape的支持

### ISSUE THREAD

**Issue by firewelly** [Yuukiy/JavSP#342]
### 功能建议

建议加入javtape.net进行支持，这个网站的片子文字比较准确，更重要的是有手工的标签，可以利用这些标签把一个艺人多个名字的合并在一起

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
欢迎pr

**Comment by Yuukiy** [comment]
先不论有多准确，站点数据非常少，随便搜了两部`IPX-177`和`FC2-718323`都没有，暂不考虑
