### ISSUE TITLE
请问为什么挂了代理.总是代理失效?代理测试有效.而且换过多个代理节点都不行

### ISSUE THREAD

**Issue by qilin72** [Yuukiy/JavSP#345]
### 问题详情

[Network]
# 是否启用代理
use_proxy = yes
# 设置代理服务器地址，支持 http, socks5/socks5h 代理。示例格式如下：
proxy = socks5h://192.168.2.2:7777
# 网络问题导致抓取数据失败时的重试次数，通常3次就差不多了
retry = 3
timeout = 10

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 运行截图（可选）

![屏幕截图 2024-07-22 140527](https://github.com/user-attachments/assets/524e9e42-a242-4cb2-82fc-27bed7434844)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by qilin72** [comment]
> ### 问题详情
> [Network]
> 
> # 是否启用代理
> use_proxy = yes
> 
> # 设置代理服务器地址，支持 http, socks5/socks5h 代理。示例格式如下：
> proxy = socks5h://192.168.2.2:7777
> 
> # 网络问题导致抓取数据失败时的重试次数，通常3次就差不多了
> retry = 3 timeout = 10
> 
> ### 运行方式
> 我运行的是打包后的exe程序
> 
> ### 代理
> 是
> 
> ### 日志
> _No response_
> 
> ### 运行截图（可选）
> ![屏幕截图 2024-07-22 140527](https://private-user-images.githubusercontent.com/10692448/350854814-524e9e42-a242-4cb2-82fc-27bed7434844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzAwMjgsIm5iZiI6MTcyMTYyOTcyOCwicGF0aCI6Ii8xMDY5MjQ0OC8zNTA4NTQ4MTQtNTI0ZTllNDItYTI0Mi00Y2IyLTgyZmMtMjdiZWQ3NDM0ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2Mjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MmYzMjc0YjVkNjY4NDUzZjMwZmVkZTljZGY1NWY4ZjEzZTQ3MjVhYzM2YTA1ZGVlYzUzZjg4ODI2OWJmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stWGFIpgdKosdMjsrMEYiUK_vNxL-2Gs2k2ShW_VHoE)
> 
> ### 提交须知
> * [x]  我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
@qilin72 除了jav321以外，别的站点也如此？

**Comment by qilin72** [comment]
> @qilin72 除了jav321以外，别的站点也如此？

是代理问题.已经解决了
