### ISSUE TITLE
在WIN系统下运行程序可以刮削里番吗，求大佬指点

### ISSUE THREAD

**Issue by zhouweijian111** [Yuukiy/JavSP#352]
### 问题详情

在WIN系统下运行程序可以刮削里番吗，求大佬指点

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
不能
