### ISSUE TITLE
建议对相同番号的电影采用附加部分命名方式来处理，即统一增加后缀-CD1、-CD2、-CDn的方式来处理放到同一文件夹内

### ISSUE THREAD

**Issue by jimmymitlavigne** [Yuukiy/JavSP#355]
### 功能建议

目前的处理方式是直接跳过这对文件整理很不友好，刮削完还要去文件夹里面翻哪些是重复的，会存在错漏和重复工作。
通过附加部分的命名方式，使它们在Emby中显示为一个完整的电影条目。部分番号存在高清和4k版本的区别这样能兼容这样的问题。而且如果确实是一模一样的后期直接删除多余的就行了。感谢！

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
没理解你在说什么
![Uploading image.png…]()

**Comment by jimmymitlavigne** [comment]
> 没理解你在说什么 ![image](https://private-user-images.githubusercontent.com/76897913/358837602-2a470b06-d1eb-402e-a895-c2b70104a8a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzI2NDYsIm5iZiI6MTcyNDAzMjM0NiwicGF0aCI6Ii83Njg5NzkxMy8zNTg4Mzc2MDItMmE0NzBiMDYtZDFlYi00MDJlLWE4OTUtYzJiNzAxMDRhOGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxNTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmY3M2Q0NjY1YjVjNzkwYmRjMDAyYWQ5MWE4MDhkYmMwYjlmNTE0MjgxZGNmZGJhYjZmNGU2OTY2Mzg4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pp2uttCJAfcqSsMGrQnG3bbkQTuTmi22Sktk64XDgu4)


抱歉可能是我没表述清楚，我并不是指分p的番号，而是指相同的番号有不同的完整文件的情况如下：
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/b42b9194-3a38-480f-bcd6-13df7fe312f3">

**Comment by Yuukiy** [comment]
@jimmymitlavigne CDn是专门用于分片的，不适合用来做清晰度的区分。你这种情况只能保留一部影片在待整理文件夹中，整理完成后移动另一部进去，比如
ABP-483 - 720p.avi
ABP-483 - 4K.mp4
https://emby.media/support/articles/Movie-Naming.html#multi-version-movies
