### ISSUE TITLE
RETOMN-070无法整理

### ISSUE THREAD

**Issue by yanwuhuo1** [Yuukiy/JavSP#358]
### 问题详情

![image](https://github.com/user-attachments/assets/9ed3905f-df18-487d-8868-53aac7086a3c)

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

正在整理: RETOMN-070.mp4
JavDB: 403 禁止访问: https://javdb365.com/search?q=RETOMN-070
无法绕开JavLib的反爬机制
命名规则导致标题被截断至空，请增大'max_path_len'或减小'max_actress_count'配置项后重试
整理失败: 无法按命名规则生成目标文件夹

### 运行截图（可选）

![image](https://github.com/user-attachments/assets/d836c5d3-637e-49ce-b91f-f051b14cce90)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
去JavSP.log里找一下这个影片的整理日志？

**Comment by Yuukiy** [comment]
@yanwuhuo1 影片标题本身不长，但是参演演员太多了，可以去配置文件里把`max_actress_count`设置的演员人数降低一点试试
