### ISSUE TITLE
女演员别名列表完善建议："吉沢明歩" 项增加“吉澤明步”

### ISSUE THREAD

**Issue by gu0o00** [Yuukiy/JavSP#359]
### 功能建议

https://github.com/Yuukiy/JavSP/blob/de19a5dc76fa65c35f0cd2b895dd565d56a36862/data/actress_alias.json#L53

建议增加：“吉澤明步”

![image](https://github.com/user-attachments/assets/36f29320-5f3d-4a2e-baa0-01e18e09c45f)

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
欢迎PR
