### ISSUE TITLE
[feature] 请问有计划添加人体分析接口进行精确剪裁封面吗？

### ISSUE THREAD

**Issue by smurfs9** [Yuukiy/JavSP#36]
可以使用百度人体分析接口对封面进行精确剪裁，解决纯数字的番号的封面裁剪不得当的问题

**Comment by Yuukiy** [comment]
> 可以使用百度人体分析接口对封面进行精确剪裁，解决纯数字的番号的封面裁剪不得当的问题

之前有考虑过百度人体分析，不过这个接口好像没有免费配额了，必须开通付费计划才能使用，按次收费。

**Comment by YanYan233** [comment]
可以用开放用自己的key，自己申请一个百度开放平台很方便的。

**Comment by YanYan233** [comment]
> > 可以使用百度人体分析接口对封面进行精确剪裁，解决纯数字的番号的封面裁剪不得当的问题
> 
> 之前有考虑过百度人体分析，不过这个接口好像没有免费配额了，必须开通付费计划才能使用，按次收费。

可以用开放用自己的key，自己申请一个百度开放平台很方便的。

**Comment by Yuukiy** [comment]
> 

我有百度开发平台账号，正是看过定价方案才没有做。你看到的是免费的么？能否给个链接？

**Comment by Yuukiy** [comment]
> 我有百度开发平台账号，正是看过定价方案才没有做。你看到的是免费的么？能否给个链接？



> > > 可以使用百度人体分析接口对封面进行精确剪裁，解决纯数字的番号的封面裁剪不得当的问题
> > 
> > 
> > 之前有考虑过百度人体分析，不过这个接口好像没有免费配额了，必须开通付费计划才能使用，按次收费。
> 
> 可以用开放用自己的key，自己申请一个百度开放平台很方便的。

我有百度开发平台账号，正是看过定价方案才没有做。你看到的是免费的么？能否给个链接？

**Comment by YanYan233** [comment]
> > 我有百度开发平台账号，正是看过定价方案才没有做。你看到的是免费的么？能否给个链接？
> 
> > > > 可以使用百度人体分析接口对封面进行精确剪裁，解决纯数字的番号的封面裁剪不得当的问题
> > > 
> > > 
> > > 之前有考虑过百度人体分析，不过这个接口好像没有免费配额了，必须开通付费计划才能使用，按次收费。
> > 
> > 
> > 可以用开放用自己的 key，自己申请一个百度开放平台很方便的。
> 
> 我有百度开放平台账号，正是看过定价方案才没有做。你看到的是免费的么？能否给个链接？

如果所有人都用你的接口很快就用完的，要是自己配置可以用1w次，基本够用了
https://ai.baidu.com/tech/body
![image](https://user-images.githubusercontent.com/42299944/157654168-abcfb266-2546-42af-a335-b87919b0cf66.png)

**Comment by Yuukiy** [comment]
`v1.2`把这个功能做进去了，需要在配置文件里进行设置，效果可以去wiki里看

**Comment by glyh** [comment]
@Yuukiy 我实现了一个[retina face](https://github.com/serengil/retinaface)后端的AI识别，请问可以PR吗？

**Comment by Yuukiy** [comment]
> @Yuukiy 我实现了一个[retina face](https://github.com/serengil/retinaface)后端的AI识别在[这里](https://github.com/Yuukiy/JavSP/compare/master...glyh:JavSP:retina?expand=1)，请问可以PR吗？

欢迎发PR~

**Comment by glyh** [comment]
> > @Yuukiy 我实现了一个[retina face](https://github.com/serengil/retinaface)后端的AI识别在[这里](https://github.com/Yuukiy/JavSP/compare/master...glyh:JavSP:retina?expand=1)，请问可以PR吗？
> 
> 欢迎发PR~

Landed here https://github.com/Yuukiy/JavSP/pull/239
