### ISSUE TITLE
希望添加指定页面抓取信息功能

### ISSUE THREAD

**Issue by nukewarrior** [Yuukiy/JavSP#360]
### 功能建议

希望添加指定页面抓取信息功能
例如 `-m  --source-url https://javdb.com/v/QV1G2q`，在手动模式下，指定抓取javdb该页面的数据并刮削。
项目对javdb的数据抓取很好，这个功能对于东洋片可能需求不大，不过通过指定页面抓取可以比较方便的在一定程度上支持西洋片的刮削。
非常感谢🙏

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
目前暂时不支持 #300
