### ISSUE TITLE
刮削完如何正确导入stash或jellyfin？

### ISSUE THREAD

**Issue by lixz123007** [Yuukiy/JavSP#363]
### 功能建议

大佬，我已经成功刮削了。使用的是通用设定。演员，视频，信息和封面都有。但是把刮削好的文件夹导入到jellyfin或stash，和没刮削还是一样的。啥信息都没有。
有没有教程链接教一下如何正确导入？感谢了！

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
jellyfin是支持的，stash似乎不支持nfo

**Comment by lixz123007** [comment]
> jellyfin是支持的，stash似乎不支持nfo

是的jellyfin已经成功了，开启nfo。但是stash确实是没有
