### ISSUE TITLE
请求添加FC2数据库：fc2ppvdb.com

### ISSUE THREAD

**Issue by whwdlxy9416** [Yuukiy/JavSP#364]
### 功能建议

正式网站为https://fc2ppvdb.com/
请求添加该站的爬虫。（FC2有好多删掉的片子，现有网站找不到）
如果可以的话，能否分享一下爬虫代码的设计思路与书写方法
本来想照着web文件夹里别的.py来改一个，但发现其代码水平远远超过了能力范围，因此发帖求更新。
谢谢

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
Dup with #346
