### ISSUE TITLE
如何只获取日文标题？

### ISSUE THREAD

**Issue by blackman-rct** [Yuukiy/JavSP#365]
### 问题详情

如题，请问如何只获取日文标题？目前好像是只要JavDB上翻译过中文的标题，优先获取到的都是中文标题，config中的title__chinese_first = no已经设置no。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
https://github.com/Yuukiy/JavSP/issues/328#issuecomment-2294810889

**Comment by blackman-rct** [comment]
> [#328 (comment)](https://github.com/Yuukiy/JavSP/issues/328#issuecomment-2294810889)

感谢，回复，按照文章中的修改建议，改完之后无法正常获取元数据，返回均为“下载封面图片失败，整理失败: 下载封面图片失败”

**Comment by blackman-rct** [comment]
> [#328 (comment)](https://github.com/Yuukiy/JavSP/issues/328#issuecomment-2294810889)

再次测试，Windows下正常，可以用就好了。感谢！
