### ISSUE TITLE
请教或者请求增加就源目录刮削不做转移的功能！

### ISSUE THREAD

**Issue by zx524724342** [Yuukiy/JavSP#366]
### 功能建议

看了规则，好像无法就视频文件源地刮削而不作转移的方式，都是刮削后进行分类到结束目录。
已经习惯了在下载时顺便对目录进行命名整理，在刮削后又被再次转移到整理完成的目录，又得手动重新操作一次弄回来，比较繁琐。

### 提交须知

- [x] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
```ini
# 整理时是否移动文件: yes-移动所有文件到新文件夹; no-数据保存到同级文件夹，不移动文件
enable_file_move = yes
```

**Comment by zx524724342** [comment]
确实是这样，感谢[Yuukiy]解惑
