### ISSUE TITLE
建议添加 openai 通用的支持第三方的 api 翻译

### ISSUE THREAD

**Issue by ikxin** [Yuukiy/JavSP#369]
### 功能建议

我看到 groq 的接口兼容 openai，尝试了从源代码运行，修改 `/web/translate.py` 中的 api 地址和模型名称，可以正常运行，建议将 groq 翻译接口改成通用型的，或者新增一个 openai 兼容接口，可以通过 `config.ini` 将 api 地址和模型名称传入进去。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
我希望javsp有这个功能，但我不希望是以出现在javsp内的方式达成的。我觉得这个软件会越来越臃肿，因此有必要设计一个插件体系来让用户实现自己想要的功能

**Comment by ikxin** [comment]
@glyh 只是将现有的 groq 翻译接口替换成可自定义 api 地址的接口，因为 groq 本身就是兼容 openai 的，所以做起来应该不难，如果可以的话我愿意发起 pr

**Comment by glyh** [comment]
可以，欢迎PR

**Comment by glyh** [comment]
Merged
