### ISSUE TITLE
[bug] 我在config修改了不优先使用中文，为什么下载回来的nfo还是中文

### ISSUE THREAD

**Issue by heptagonlin** [Yuukiy/JavSP#37]
[bug] 我在config修改了不优先使用中文，为什么下载回来的nfo还是中文

**Comment by YanYan233** [comment]
换站点顺序试试看javbus，javdb应该都是日文的

**Comment by Yuukiy** [comment]
> [bug] 我在config修改了不优先使用中文，为什么下载回来的nfo还是中文

airav提供的数据是中文的，如果完全不想要中文，可以去掉下面配置文件里爬虫列表中的```airav```
```ini
[CrawlerSelect]
normal = airav,avsox,javbus,javdb,javlib,jav321,mgstage,prestige
```

**Comment by heptagonlin** [comment]
好的，谢谢。我试试
