### ISSUE TITLE
希望通过指向url地址进行刮削

### ISSUE THREAD

**Issue by MasticoreChen** [Yuukiy/JavSP#373]
### 功能建议

在进行刮削，经常会出现番号重复刮削失败的情况，希望可以手工指向url进行刮削

正在整理: [073124-001].mp4
web.javdb: '073124-001': 存在2个完全匹配目标番号的搜索结果
下载封面图片失败
整理失败: 下载封面图片失败

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by MasticoreChen** [comment]
以073124-001为例，在javbus中只有一个，但是如果从javbus刮削的话会出现整理失败: 下载封面图片失败。改为javdb的话，有两个是相同的，无法如faq里那样添加日期来标注。

**Comment by MasticoreChen** [comment]
https://javdb.com/v/Mbb4Pv & https://javdb.com/v/ZNNp9J

**Comment by Arkshiaho** [comment]
好像现在依旧没办法使用这种手工指向URL进行定向刮削的方法，我在挂七泽米亚的MIDV-018的时候就撞车了
