### ISSUE TITLE
Make English the default language of this repo

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#375]
### 功能建议

Although I would like to contribute to this repo. I don't want to get myself into legal troubles. I think it would be better to use English as the default languages so it kinda raise the bar for learning this software. This can result in smaller user base and in reduce the chances of getting ourselves into any kind of trouble. 

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你是指commit记录还是Wiki和软件运行时的提示消息？如果是后者，我不赞同为了躲避审查而影响用户使用。如果你担心法律风险，请考虑用一个不能关联你真实身份的账号或者暂停维护。

**Comment by glyh** [comment]
Make sense.
