### ISSUE TITLE
新增爬虫劇照相關功能

### ISSUE THREAD

**Issue by iiooiioo888** [Yuukiy/JavSP#379]
### 功能建议

新增爬虫劇照相關功能

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
已实现：
https://github.com/Yuukiy/JavSP/blob/d964c98e37d8ac7cd93ba3d3d6db3868e34298be/config.yml#L118

**Comment by glyh** [comment]
https://github.com/Yuukiy/JavSP/actions/runs/11048855319
