### ISSUE TITLE
proxyfree client broken

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#383]
![微信图片_20240927120928](https://github.com/user-attachments/assets/21b5377c-02b1-422c-a09b-4c561f99dc2d)

_Originally posted by @qicfan in https://github.com/Yuukiy/JavSP/issues/378#issuecomment-2378363446_

**Comment by glyh** [comment]
@qicfan 我修复了一下，请在测试下，谢谢

**Comment by qicfan** [comment]
出了个新问题，跑不起来了，报错如图
![微信图片_20240927124756](https://github.com/user-attachments/assets/c39f42be-8e84-4a87-9317-173ed95ae143)

**Comment by glyh** [comment]
……这个应该不是JavSP的问题，跑下`which poetry`看看poetry是不是被误删了

**Comment by qicfan** [comment]
切到d964c98以后可以跑，但是报错了，可能是跟master的包不同。但是再切回master就又报非法指令了，具体如图，我觉得还是master有问题。
![微信图片_20240927130709](https://github.com/user-attachments/assets/d7e8deaf-0d09-4c5d-bf82-10aa74a974d9)

**Comment by glyh** [comment]
因为CI在windows下可以运行，我在linux下可以运行，所以我还是不确定。试试这个？
```
$ poetry shell
# 在poetry shell下：
$ python javsp/__main__.py
```

**Comment by glyh** [comment]
哦对了，master和 配置重构之前的python版本是不一样的，现在python最低版本是3.10（参见changelog）

**Comment by glyh** [comment]
CI现在在 linux, win 和macos(x64)下分别构建二进制了：
https://github.com/Yuukiy/JavSP/actions/runs/11065111009

**Comment by qicfan** [comment]
我是debian12，python3.11，master更新到最新，还是不行。

d964c98版本没问题，如图：
![微信图片_20240927134408](https://github.com/user-attachments/assets/0e0f6a70-e0f3-4418-b31d-8922f6083be7)

master问题依旧，如图：
![微信图片_20240927134500](https://github.com/user-attachments/assets/c0a1a297-43fd-4d53-b2d8-25a033093efa)

**Comment by glyh** [comment]
> 因为CI在windows下可以运行，我在linux下可以运行，所以我还是不确定。试试这个？
> 
> ```shell
> $ poetry shell
> # 在poetry shell下：
> $ python javsp/__main__.py
> ```
> 
> 或者可以试试把`~/.cache/pypoetry/virtualenvs/`删除，然后在git root重新跑:
> 
> ```shell
> $ rm -rf ~/.cache/pypoetry/virtualenvs/
> $ poetry install
> $ poetry run javsp
> ```
> 
> 我倾向于怀疑你的virtual environment挂了

按照这里跑一下试试

**Comment by qicfan** [comment]
确认是[d103767](https://github.com/Yuukiy/JavSP/commit/d103767e870fe16ada6bfaf7774658fbc1777711)这个版本引入的问题，改动比较多，还没细看，等我抽空研究下。

**Comment by qicfan** [comment]
确认问题在：./javsp/cropper/slimeface_crop.py:5
`from slimeface import detectRGB`

**Comment by glyh** [comment]
请问有错误信息吗？

**Comment by qicfan** [comment]
没有，我看了下slimeface，接口在so里，怀疑跟平台有关，你不报错可能是环境刚好都满足

**Comment by qicfan** [comment]
我这个debian12刚装的虚拟机，啥依赖都没装过，可能确实环境有问题。

**Comment by glyh** [comment]
https://github.com/Yuukiy/JavSP/issues/384
