### ISSUE TITLE
[bug] 在开启VPN代理的时候，软件是会run代码然后退出

### ISSUE THREAD

**Issue by Jyurineko** [Yuukiy/JavSP#39]
### bug详情
在开启VPN代理的时候，软件是会run代码然后退出，无论config文件中有没有设置 use_proxy = yes，都一样情况
没有开启VPN代理的时候，能正常运行，唯一区别就是提示会有功能缺失，
V1.1和v1.3都是同样的问题

[Network]
是否启用代理
use_proxy = yes
设置代理服务器地址，支持 http, socks5/socks5h 代理。示例格式如下：
proxy = http://127.0.0.1:10809        （这里是我VPN的系统代理地址，之前都没问题）
网络问题导致抓取数据失败时的重试次数，通常3次就差不多了
retry = 3
timeout = 10

**Comment by Jyurineko** [comment]
V1.4没问题了0 0....Actions里找到了临时版，没问题了。（多谢老哥的软件）

**Comment by Yuukiy** [comment]
> V1.4没问题了0 0....Actions里找到了临时版，没问题了。（多谢老哥的软件）

没事……总之解决就好……不过是话说问题是bug么？还是误会什么的？要是bug的话还有点在意

**Comment by Jyurineko** [comment]
就是1.08和1.1版本，复现的话就是：
1. V2rayN这个软件，启动系统代理
![1](https://user-images.githubusercontent.com/36675941/156102911-0993182b-875d-4c07-ad6b-bebb5fc4a6f4.png)
![2](https://user-images.githubusercontent.com/36675941/156103108-8c7d44c7-fabb-4e8c-84a4-82e2877369c8.png)
V2rayN会自动配置电脑那个代理。这个是前置条件

2. 打开JavSP1.08和1.1版本。会run一个terminal，然后run完直接退出。
2.1 如果关闭V2rayN软件，是会正常打开的，检查更新和打开预整理的文件夹。
2.2 但是打开V2rayN软件，把config里面的network里面的use_proxy=no，也是run terminal，直接退出的。 所以不清楚是不是与系统的翻墙环境有关系。因为1.4版本和1.0一样，都是一切正常的，

————————————————————
PS：因为我看V1.4好像修改了长文件名的处理方式，但是windows好像对番号名里面有星星的那种字符要占很多字符。所以在转移文件的时候还是会报文件名太长了。就是软件本身保存的时候，文件名长度没问题，但是在复制黏贴到其他文件夹的时候会报文件名太长。avair中文到不长，就是没中文的时候通过javbus，javdb的时候用日语的时候会这样。因为报错长名字的都是日语

虽然文件名好像大家都想完整保存，不知道能否截断成固定的长度

**Comment by Yuukiy** [comment]
@Jyurineko 增加了一个选项来自定义最大路径长度，同时增加了对女优数的限制：避免标题太长或者女优太多时整理失败

**Comment by Jyurineko** [comment]
感恩老哥，看到config里面的option了
