### ISSUE TITLE
在config.ini里编辑了filename = $num #$actress后，生成的封面和nfo文件名不包含$num #$actress这两项

### ISSUE THREAD

**Issue by c2s1s1** [Yuukiy/JavSP#397]
### 问题详情

fanart.jpg
movie.nfo
poster.jpg
都是这三个名称

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by c2s1s1** [comment]
[config.txt](https://github.com/user-attachments/files/17302487/config.txt)
配置文件

**Comment by c2s1s1** [comment]
另外在enable_file_move = no时
运行后不会重新命名原视频文件

**Comment by jiezhengj** [comment]
我也有相同问题

**Comment by Yuukiy** [comment]
![image](https://github.com/user-attachments/assets/bb05bdb9-44fa-405c-8072-241bc50f9d27)
