### ISSUE TITLE
将我移动走的文件，给我恢复回去。

### ISSUE THREAD

**Issue by Leelagozero** [Yuukiy/JavSP#415]
### 问题详情

我之前的文件夹有影片的发布时间，片子的质量等很丰富的信息，这个软件给我强制移动走了。现在上T的文件都乱了，我想知道你怎么能给我恢复呢！

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by ds0tm8340** [comment]
不是大哥，你怎么下个软件就直接运行的，不先读一下说明或者试一下么

**Comment by Leelagozero** [comment]
最基本的！软件不能修改人家原来的东西啊！你可以生产你自己认为好的。

**Comment by Leelagozero** [comment]
TNND。我那些带字母的片子，也都给我全部移走了，字幕文件没有移走，我要恢复这些需要几天时间。这个软件煞笔到了没有边界的程度了。你NND大可以在我原来的文件夹里面增加封面（其实我都有了封面截图了），就傻呵呵的将我的视频文件移走了，自己还创建了文件夹名字。我实在是无语了。各位千万别用这个软件，用之前你需要双份备份。不然你的文件就被他毁了。切记切记。

**Comment by qicfan** [comment]
**能来GITHUB难道一点基本素养都没有么？**

你用不能给开发者带来任何收益，你不用也不能给开发者带来任何损失！你把这儿当微博了么，诋毁几句就能消灭一个项目，想啥呢？

**Comment by LeovYin** [comment]
作者readme确实没有写清楚，但是你难道不会自己测试一个文件试试吗？你那么多资源，在设置了反反爬机制下，肯定得跑至少一小时，跑的时候不会看看吗？

**Comment by Yuukiy** [comment]
所有的移动都会单独记录到一个日志文件`FileMove.log`，你可以根据此文件还原你原本的文件结构，要写对应的脚本很简单，随便找个AI工具都可以。

这是个开源项目，从未获利过哪怕一分钱。希望你清楚，我并不欠你什么。

**Comment by Leelagozero** [comment]
我知道那个文件，主要是数据量太大了，我也不会脚本。要手动移动回来，估计需要好几天。

建议，不这么搞，之前都是备份出来刮的，你这个随便就移动走了，而且字幕文件都没有带走。

**Comment by LeovYin** [comment]
> 我知道那个文件，主要是数据量太大了，我也不会脚本。要手动移动回来，估计需要好几天。
> 
> 建议，不这么搞，之前都是备份出来刮的，你这个随便就移动走了，而且字幕文件都没有带走。

config.yml里可以设置不移动：
summarizer:
  # 整理时是否移动文件: true-移动所有文件到新文件夹; false-数据保存到同级文件夹，不移动文件
  move_files: true

**Comment by glyh** [comment]
> > 我知道那个文件，主要是数据量太大了，我也不会脚本。要手动移动回来，估计需要好几天。
> > 建议，不这么搞，之前都是备份出来刮的，你这个随便就移动走了，而且字幕文件都没有带走。
> 
> config.yml里可以设置不移动：
> 
> ```
> summarizer:
>   # 整理时是否移动文件: true-移动所有文件到新文件夹; false-数据保存到同级文件夹，不移动文件
>   move_files: true
> ```

这个是未release版本的配置。已经release的1.7.x还是使用config.ini

**Comment by bennyz327** [comment]
世界奇觀，使用說明不看，READM也不看，直接執行然後開 issue 抱怨
秀下限也沒看過這個好笑了

**Comment by glyh** [comment]
I don't think this is a bug/feature. And I do wish the pointless argue to stop.
