### ISSUE TITLE
一些源代码的BUG

### ISSUE THREAD

**Issue by LeovYin** [Yuukiy/JavSP#416]
### 问题详情

第一个BUG：在config.yml设置完了百度翻译API后翻译值返回None
**经过我的读代码之后，发现竟然是翻译的py中没有写return。。。只有rtn没有return，害我排查半天**
第二个BUG：部分网站剧照无法获取，例如[https://wiki-img.airav.wiki/storage/sections/172884_002.jpg](url)
这个网站我用普通的requests下载都下不了，由于我没有学过python语言，不知道怎么修改
但是[https://pics.dmm.co.jp/digital/video/h_1116cafr00347/h_1116cafr00347jp-20.jpg](url) 这个dmm却可以正常获取，希望有人可以解决一下。

### 运行方式

我是从源代码运行的

### 代理

是

### 日志

第一个BUG
------------------------------------
<string> 1 <module>
"<string>", line 1

__main__.py 600 entry
"D:\TOOL\JavSP\javsp\__main__.py", line 600
RunNormalMode(recognized + recognize_fail)

__main__.py 441 RunNormalMode
"D:\TOOL\JavSP\javsp\__main__.py", line 441
success = translate_movie_info(movie.info)

translate.py 29 translate_movie_info
"D:\TOOL\JavSP\javsp\web\translate.py", line 29
if 'trans' in result:

第二个bug
整理影片:   0%|          | 0/1 [00:28<?, ?it/s]
Downloading extrafanart 1 from url: https://wiki-img.airav.wiki/storage/sections/173275_002.jpg:  75%|#######5  | 6/8 [00:28<00:06,  3.01s/it]
#整理完成\AIKA\[PPPD-483] 开发乳腺性诊所/extrafanart/1.png
False
                                               
下载的图片1.png无效
**(此处原先的代码并不会提示，并且抛出错误后会直接退出，非常不方便)**

### 运行截图（可选）

![Clip_2024-10-26_16-30-45](https://github.com/user-attachments/assets/ba7da2dd-3551-4f0c-bc01-ab2baeae88c8)
![Clip_2024-10-26_16-34-51](https://github.com/user-attachments/assets/f0eec539-caae-40d0-9a38-ca1ef85cf131)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by LeovYin** [comment]
问题已解决，这个网站有反爬虫，把airav从config.yml删掉就行。现在已经非常完美了。感谢作者的辛勤付出！！！小弟膜拜膜拜

**Comment by glyh** [comment]
所以现在是只有第一个bug吗？我今晚上有空修一下

**Comment by LeovYin** [comment]
> 所以现在是只有第一个bug吗？我今晚上有空修一下或者如果你方便的话可以交个PR吗？
> 
> 顺便，你用的是master的代码吗？

对，translate.py的 74line，还有下面的，都没写return。然后发现删掉airav之后，部分封面无法获取，然后导致程序中断。这对我有大量文件需要整理十分不友好，我打算弄一个中断但不退出程序，并返回错误日志，之后我单独整理就行。但我才接触系统编程几个月可能能力不怎么够

**Comment by glyh** [comment]
其实这个软件在整体性重构，只不过我最近没时间去写 https://github.com/Yuukiy/JavSP/pull/391
