### ISSUE TITLE
从源码运行如何打开日志？

### ISSUE THREAD

**Issue by popstk** [Yuukiy/JavSP#419]
### 功能建议

从源码运行master分支，搜索了一遍代码，没有看到有关日志的设置，比如Level 输出到文件，这是要自己加上吗？

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
master在重构，我之前重构网络接口，结果发现基本上重写了一遍……之后重构完会加入日志功能

**Comment by popstk** [comment]
https://github.com/Yuukiy/JavSP/pull/391  作为 long runing的服务有哪些改造，已经用cron作定时任务，似乎也没啥问题，就是日志这块缺少？

**Comment by glyh** [comment]
那个可能是更远的目标，把架构改成类似http server一样。 这次重构主要目的是提升效率（并行处理多个影片）以及还清技术贷
