### ISSUE TITLE
下载封面 图片失败

### ISSUE THREAD

**Issue by dyshzcl** [Yuukiy/JavSP#423]
### 问题详情

下载封面 图片失败 有这样的提醒

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by glyh** [comment]
你这问题描述也太敷衍了吧 有排查过不是自己的网络问题吗？

**Comment by dyshzcl** [comment]
也可能跟网络，有关系，我用了日本ip，不好判断，只要大家没有这个问题，就是我网络问题，还有今天出现如下提醒：
HTTP 429: Too Many Requests: Google翻译请求超限，将等待131秒后重试

**Comment by Hapihapiha** [comment]
我用的1.8版本没问题，但测试版本1.8.61，1.8.60等版本封面图和艺术图都是同一张，poster变成和fanart一样的横幅图了！

**Comment by Izumiko** [comment]
@Hapihapiha 新版裁剪部分的代码有问题，按照我这个issue #462 的方法改一下代码就能正常裁剪了

**Comment by glyh** [comment]
Duplicate #462
