### ISSUE TITLE
之前使用的是config.ini，请重新配置JavSP，或者通过这个脚本来将其迁移到最新的config.yml，到底怎么配置啊？！！！

### ISSUE THREAD

**Issue by Hapihapiha** [Yuukiy/JavSP#427]
### 功能建议

大佬，就不能重新打包一下吗？这个真不知道怎么弄啊！不是程序员真一点都不懂啊！目前这个1.8版本刮削完生成的nfo和图片没法命名啊！同个文件夹放一起就被覆盖了！

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
1.8 还没release，很多critical的功能没有实现。
配置可以参见这里：https://github.com/Yuukiy/JavSP/blob/master/config.yml
配置迁移可以使用：https://github.com/Yuukiy/JavSP/blob/master/tools/config_migration.py
但是似乎有用户回馈这个脚本在旧的python版本中无法运行
