### ISSUE TITLE
可否支持硬链接方式整理，方便PT下载内容的整理

### ISSUE THREAD

**Issue by idanfang** [Yuukiy/JavSP#434]
### 功能建议

可否支持硬链接方式整理，方便PT下载内容的整理

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by cnzgray** [comment]
可以的，见这个配置

https://github.com/Yuukiy/JavSP/blob/13fa5aef40b79c87de612bcd30461cd0ddef265f/config.yml#L86

**Comment by idanfang** [comment]
> 可以的，见这个配置
> 
> https://github.com/Yuukiy/JavSP/blob/13fa5aef40b79c87de612bcd30461cd0ddef265f/config.yml#L86


你好，我下载了 JavSP-1.8.63-WINDOWS-lastest 版本
并且修改相关参数
如图红色框内

依然源文件被移除出 PT 下载目录，不知哪里出了问题

<img width="642" alt="3b22da0a4ef727842bc71d2ad028c13d" src="https://github.com/user-attachments/assets/588885a5-7e6f-45f9-ac7e-25107ecd59f3">
<img width="701" alt="8ab80ca2419813d55c8ff58aca3691fe" src="https://github.com/user-attachments/assets/7c87f84e-c572-4f1d-b2f8-2feb6a1ccb60">

**Comment by idanfang** [comment]
搞定了，原来拼写错误。
然后发现翻译这里，engine: google 程序直接关机

然后还有两个小问题
如图，一个是反爬，一个是网络错误
![Uploading IMG_2736.jpeg…]()

**Comment by idanfang** [comment]
![IMG_2736](https://github.com/user-attachments/assets/58201112-fdcd-4339-bfe5-79e249150646)

**Comment by glyh** [comment]
麻烦针对其他问题重新开Issue，这样方便维护者工作，谢谢！

**Comment by mcdullmedia** [comment]
不太理解.  
不是說 
move files : false
hard_link: true 
這樣才對嗎?
