### ISSUE TITLE
[feature] plex对头像支持不好，可以开发一下女友头像支持plex的功能吗？

### ISSUE THREAD

**Issue by heptagonlin** [Yuukiy/JavSP#45]
[feature] plex对头像支持不好，可以开发一下女友头像支持plex的功能吗？
或者增加一下女优头像的链接，因为搔刮回来的NFO有些有头像链接，有些没有。对于我们这些用plex的很苦恼。

**Comment by Yuukiy** [comment]
没明白

> [feature] plex对头像支持不好，可以开发一下女友头像支持plex的功能吗？ 

具体是指什么？plex需要特殊的女优头像？

> 或者增加一下女优头像的链接，因为搔刮回来的NFO有些有头像链接，有些没有。对于我们这些用plex的很苦恼。

没有女优头像的，是因为在刮削的时候，影片页面就没有头像

**Comment by heptagonlin** [comment]
有部分影片，生成的nfo文件中有女优头像的链接，但有的影片没有，这个能不能强制生成女优头像链接？？

**Comment by Yuukiy** [comment]
不能。没有女优头像的，是因为在刮削的时候，影片页面就没有头像
