### ISSUE TITLE
fc2ppvdb 能连通 但无法绕过CloudFlare检测

### ISSUE THREAD

**Issue by 457-crtrl** [Yuukiy/JavSP#451]
### 问题详情

使用proxy确认可以连通 但是无法绕过CloudFlare检测

### 运行方式

我是从源代码运行的

### 代理

是

### 运行截图（可选）

![Snipaste_2024-11-26_20-14-36](https://github.com/user-attachments/assets/ec84cef6-13cc-4982-8e89-2905c35c4690)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by maodun96** [comment]
网络问题，我这边没问题。
![image](https://github.com/user-attachments/assets/78aa86fb-fa84-41ac-8550-034c38de89d9)

**Comment by glyh** [comment]
我也测试了下，确实是你自己的网络问题
