### ISSUE TITLE
不会用啊，能不能直接做个UI图形界面程序，方便省事

### ISSUE THREAD

**Issue by aip5** [Yuukiy/JavSP#459]
### 功能建议

不会用啊，能不能直接做个UI图形界面程序，方便省事

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by glyh** [comment]
欢迎PR

**Comment by qicfan** [comment]
[JavSPN](https://github.com/qicfan/JavSPN)

半成品，但是可以将就用。

**Comment by QYG2297248353** [comment]
[AMMDS](https://github.com/QYG2297248353/AMMDS-Docker)

类似的，只有Docker版本
