### ISSUE TITLE
封面使用默认裁剪方法比例出错

### ISSUE THREAD

**Issue by Izumiko** [Yuukiy/JavSP#462]
### 问题详情

```yaml
    crop:
      engine: null # null表示禁用图像剪裁
```

输出的poster就是fanart本身，并未裁剪。`DefaultCropper`类写错了

旧版：
https://github.com/Yuukiy/JavSP/blob/f301bf8288b2eba06ad8462d63eb7543bb1a25c8/core/image.py#L38

新版：
https://github.com/Yuukiy/JavSP/blob/13fa5aef40b79c87de612bcd30461cd0ddef265f/javsp/cropper/interface.py#L22

应该把`DefaultCropper`的最后几行写为：
```python
        dh = int((fanart_h - poster_h) / 2)
        box = (fanart_w - poster_w, dh, fanart_w, poster_h + dh)
        return fanart.crop(box)
```
这样才是裁剪fanart右半中间部分

### 运行方式

我是从源代码运行的

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by glyh** [comment]
已经修复了，麻烦测试下

**Comment by Izumiko** [comment]
return那行还是返回的原始fanart，没裁剪

**Comment by glyh** [comment]
啊 好的 😂

**Comment by glyh** [comment]
80904a0
