### ISSUE TITLE
下载封面图片失败导致刮削中断（实际上已经下载成功）

### ISSUE THREAD

**Issue by autotypezzzz** [Yuukiy/JavSP#466]
### 问题详情

1、运行环境：win11 23h2 + Cloudrdrive2 + 挂载115云到本地盘
2、Javsp 版本 V1.8

运行exe打包版本，在看到图片下载进度条后，提示图片下载失败，然后退出刮削。查看了Clouddrive2的后台进度，v1.8提示下载失败之后过了一段时间图片才上传到Clouddrive2里面，并在挂载的本地磁盘中展示出来。

log中的这一条冲突我认为值得注意：

OSError: [WinError 1005] 此卷不包含可识别的文件系统。
请确定所有请求的文件系统驱动程序已加载，且此卷未损坏。: 'A:\\.媒体库\\FC2 - JAVSP v1.8\\#整理完成\\一条みお\\[FC2-2932490]\\FC2-2932490-CD1-fanart.jpg'

可能是因为clouddrive还没上传完毕，而v1.8已经在向磁盘请求文件路径，导致bug，可否请开发者修复？感激不尽。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/user-attachments/files/18092125/JavSP.log)

### 运行截图（可选）

![image](https://github.com/user-attachments/assets/ed320aaa-90a5-4f0b-b332-6831649a1bf3)
![image](https://github.com/user-attachments/assets/822066aa-da62-43e0-96de-6df9bf4427ca)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by autotypezzzz** [comment]
1、补充一些CD2挂载的相关信息：由于目前CD2挂载115云并在emby / jellyfin大规模扫库和上传刮削文件时易触发风险管控，所以CD2的开发者将请求115网盘接口的QPS大幅下调，就导致即使上传小文件（例如nfo 图片）也会处于比较小的速度。

2、另外，CD2还有目录缓存持久化这一特性，导致挂载本地盘中的文件读取需要等待很久的时间（或者手动刷新）
![image](https://github.com/user-attachments/assets/992b6db2-f820-4491-bb17-16007a38c486)

3、目前我仍用v1.7.3就并未发现上述的问题，对于fc2某些站点由于关站和javdb删除了相关页面导致fc2刮削失败的项目，尝试使用了v1.8新增的几个元数据网址均能很好的刮削。

4、所以在此请求作者可以给1.7.x版本再增加最后一个小patch，只加入fc2的新刮削站点即可，能够使v1.7.x先继续苟着一段时间。

**Comment by qicfan** [comment]
我有另一个工具 [q115-strm](https://github.com/qicfan/q115-strm)可以解决115的问题

**Comment by glyh** [comment]
Duplicate #453
