### ISSUE TITLE
配置的抓取器无效: msin /// main:116 ERROR: list index out of range

### ISSUE THREAD

**Issue by fuchenw** [Yuukiy/JavSP#472]
### 问题详情

没有做任何改动忽然无法使用，更新版本依旧报错

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/user-attachments/files/18129945/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by Lkskywalker** [comment]
请问这个问题怎么解决，我也遇到了

**Comment by fuchenw** [comment]
> 请问这个问题怎么解决，我也遇到了

解决了，直接开一个新的文件夹，重新生成配置文件就好了，不知道什么原因之前的配置文件BUG了
