### ISSUE TITLE
[feature] Can you add English support for title and for nfo file

### ISSUE THREAD

**Issue by aviarad3** [Yuukiy/JavSP#48]
### 功能描述
描述你希望添加的功能或者功能建议

如果你希望开发针对某个站点的抓取器，需要提供以下信息：
- 此站点的地址
- 从此站点获得的资源的较为通用的文件夹结构、文件名等

### 方案建议
如果你对此功能有思路和方案，请描述

### 其他信息
截图、示意图等用来描述这个功能点的信息

**Comment by Yuukiy** [comment]
For the project itself, currently I don't have enough time to maintain it with multiple-language support.
I'm open to accept PRs that translate our README or any part of the software into English. You’re welcome to submit one :)

For the nfo file, most of the websites, where the crawlers get data from, only provide their sites with Japanese (only airav provides Chinese). So, it might not be available to generate nfo file with English. You could check if there is any translation tool for your media server (Jellyfin, Emby or something else).
