### ISSUE TITLE
[crawler] javlib在某些情况下无法爬取

### ISSUE THREAD

**Issue by whj34547** [Yuukiy/JavSP#49]
例如番号XXX-001，XXX-010之类的，在javlib下搜索会反馈出很多近似番号而不是指定番号页面，从而导致爬取失败，希望作者大大看能否解决，YYSY javlib的相关信息最全更新最及时，这是db和bus比不了的

**Comment by Yuukiy** [comment]
给个具体的番号啊
![image](https://user-images.githubusercontent.com/76897913/157057266-6695b60c-8f9b-4de9-9fbd-7410be87a4ea.png)

**Comment by whj34547** [comment]
ipx-001
abw-001
enki-001
等等这些只要是001或者010结尾的，在javlib上搜索就会出现多个结果而不是确定结果

**Comment by Yuukiy** [comment]
已修复，是番号非大写导致的问题。可到 https://github.com/Yuukiy/JavSP/actions/workflows/pyinstaller.yml 下载修复后的版本使用
