### ISSUE TITLE
[bug] 在抓取时出现一个无法保存图片、nfo的bug

### ISSUE THREAD

**Issue by Jyurineko** [Yuukiy/JavSP#58]
### bug1详情
FC2-1633548
FC2-2713323

cannot write mode P/RGBA as JPEG

### 如何复现
配置的话 无改动，除了把免代理的javdb36 改成 38

### 日志
[JavSP.log](https://github.com/Yuukiy/JavSP/files/8317360/JavSP.log)

### 截图（可选）
![微信图片_20220322004126](https://user-images.githubusercontent.com/36675941/159311593-311f79c5-bd00-4a59-9f57-8e700083ce1c.png)
![微信图片_20220322004129](https://user-images.githubusercontent.com/36675941/159311600-3573e5b1-17cc-415e-8eb5-766eb239c1f2.png)

——————————————————————————————————————————————
PIL好像要convert()转格式？ 貌似下载的高清图中有A通道的 有个P模式我不太懂
![image](https://user-images.githubusercontent.com/36675941/159312449-db94b852-38a2-4049-93a6-1f65213c9f66.png)

————————————————————————————————————————————————
### bug2详情
FC2-1633548
FC2-2713323

同样以fc2为例子，在版本1.1.11以及之后12-15 对于fc2的识别都会报这个错误，导致fc2搜刮失败
版本1.1.10以及以前的版本 不会报这个错误正常搜刮 上个bug的截图可以看到，只是会有PIL读存报错

### 如何复现
配置的话 同上 无改动，除了把免代理的javdb36 改成 38

### 日志
[JavSP.log](https://github.com/Yuukiy/JavSP/files/8317430/JavSP.log)

### 截图（可选）
![微信图片_20220322004920](https://user-images.githubusercontent.com/36675941/159313220-4edc2e27-de3f-4428-82c6-9b6847e35bf9.png)

**Comment by Yuukiy** [comment]
确实是1.1.11引入的bug，已经修复，可以到 https://github.com/Yuukiy/JavSP/actions/runs/2032823396 下载修复的版本使用

**Comment by Jyurineko** [comment]
那个.....bug1中cannot write mode P/RGBA as JPEG问题好像依然存在...不过不急0 0
[JavSP.log](https://github.com/Yuukiy/JavSP/files/8342165/JavSP.log)

**Comment by Yuukiy** [comment]
又修复了一次，你试试 https://github.com/Yuukiy/JavSP/actions/workflows/pyinstaller.yml

**Comment by Jyurineko** [comment]
嗯...都没问题了...谢谢您
