### ISSUE TITLE
[bug] 1.0以上版本弹错

### ISSUE THREAD

**Issue by chriiori2** [Yuukiy/JavSP#61]
### bug详情
![图片](https://user-images.githubusercontent.com/17594964/161396882-54ea08b5-7676-42f6-9f16-b60aec10c90c.png)

### 如何复现
删除过配置文件也尝试过了
### 日志
日志没有任何内容

**Comment by chriiori2** [comment]
已解决= =不知道哪里多打了个字符

**Comment by Yuukiy** [comment]
解决的话我就关了。你截图的区域很小也不足以定位问题
