### ISSUE TITLE
1.2版本报错闪退

### ISSUE THREAD

**Issue by qinfeng22222** [Yuukiy/JavSP#62]
### bug详情
![QQ截图20220403094859](https://user-images.githubusercontent.com/98304506/161407755-da500b31-ba4d-41bf-8be6-5057fcda484c.png)

闪退报错，重新下载替换及删除配置文件依旧

**Comment by Yuukiy** [comment]
抓取哪部影片的时候出的问题？
要不你把同目录下的`config.ini`和`JavSP.log`两个文件传一下？我这里没有遇到这个问题

**Comment by qinfeng22222** [comment]
手动处理了，不知道是哪部了，但应该都是无码的数字番号

**Comment by keene1** [comment]
这个问题我也遇到了，一样的报错
