### ISSUE TITLE
部分番号无法获取到信息

### ISSUE THREAD

**Issue by qinfeng22222** [Yuukiy/JavSP#63]
例如 abp055，是否是因为中间没有字符
![image](https://user-images.githubusercontent.com/98304506/161662174-f2a0296a-06f5-405b-812c-3076158e78b9.png)

**Comment by Yuukiy** [comment]
这个问题是由于`abp055`被优先识别为cid（仅用于fanza网站）导致的。对类似情况做了处理并且增加了备用机制，可以到 https://github.com/Yuukiy/JavSP/actions/runs/2096368605 下载临时释放版使用
