### ISSUE TITLE
[feature] 希望开发115网盘刮削功能

### ISSUE THREAD

**Issue by Xiedeyu** [Yuukiy/JavSP#64]
### 功能描述
我觉得可以再加个针对115的刮削器，更侧重管理，对文件分片可以放弃

### 方案建议
如果用上115网盘的话，受众应该会更广一些。115的接口很好懂，安全性全靠cookie，我自己做过的感受。115的标签可以用来快速拿出自己想看的。

### 其他信息
截图、示意图等用来描述这个功能点的信息

**Comment by Yuukiy** [comment]
可以将115网盘挂载到本地，映射成本地盘符后进行刮削。JavSP不会支持直接对115的刮削

**Comment by Xiedeyu** [comment]
> 
好吧
