### ISSUE TITLE
[bug] 在___时出现一个___的bug

### ISSUE THREAD

**Issue by hentaimiku10** [Yuukiy/JavSP#67]
![{42BSEKO 3YZ)CW$IP6FL%E](https://user-images.githubusercontent.com/103306178/162561961-ee25a359-e384-4881-9a2d-5498840c72f7.png)
 这个要咋弄？打开直接关了

**Comment by Yuukiy** [comment]
传一下你的配置文件

**Comment by Yuukiy** [comment]
无反馈
