### ISSUE TITLE
无码高清番号提取错误

### ISSUE THREAD

**Issue by qinfeng22222** [Yuukiy/JavSP#68]
无法提取类似番号![image](https://user-images.githubusercontent.com/98304506/163086678-5555ff2d-0474-4a16-afa6-1fbc0137a39b.png)

**Comment by Yuukiy** [comment]
只有`MKBD-S00`这个系列有这个问题么？

**Comment by qinfeng22222** [comment]
MKBD的部分有问题

**Comment by qinfeng22222** [comment]
之前尝试删除过正则表达式，但这个系列依然会有一些问题
