### ISSUE TITLE
番号无法获取到title，但实际很容易搜到是什么原因

### ISSUE THREAD

**Issue by qinfeng22222** [Yuukiy/JavSP#75]
### 问题详情

如图上的番号031115-042在几个主要网站都能直接搜到，
![QQ截图20220507145111](https://user-images.githubusercontent.com/98304506/167242736-bc1380ca-f38c-4cc0-a311-1c94595b2071.png)
![QQ截图20220507145055](https://user-images.githubusercontent.com/98304506/167242740-7641c908-5cda-41dd-90f1-4f4f4f17d15b.png)
![QQ截图20220507145206](https://user-images.githubusercontent.com/98304506/167242744-7969cc1d-f3cd-4da3-8193-cbb0bc7d6e6e.png)

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/8644625/JavSP.log)

### 运行截图（可选）

![QQ截图20220507144616](https://user-images.githubusercontent.com/98304506/167242755-57cb0cea-7ba9-4d11-bad1-5d81c35c0a51.png)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
需要把你的原始文件命名为`031115_042`（使用下划线分隔）。截图里使用的是`-`分隔的`031115-042`，因此在抓取数据时抓不到对应影片的数据。
由于某些影片，例如`050121_001`和`050121-001`仅仅有下划线和连词符的差异，但是是两部不同的影片，因此软件里在遇到纯数字番号时是保留原始分隔符形式的，不会也不能进行强行转换

**Comment by qinfeng22222** [comment]
多谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yuukiy/JavSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 晚上11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yuukiy/JavSP] 番号无法获取到title，但实际很容易搜到是什么原因 (Issue #75)





 
需要把你的原始文件命名为031115_042（使用下划线分隔）。截图里使用的是-分隔的031115-042，因此在抓取数据时抓不到对应影片的数据。
 由于某些影片，例如050121_001和050121-001仅仅有下划线和连词符的差异，但是是两部不同的影片，因此软件里在遇到纯数字番号时是保留原始分隔符形式的，不会也不能进行强行转换
