### ISSUE TITLE
麻烦作者设置文件命名长度限制

### ISSUE THREAD

**Issue by ZhiyuanEric** [Yuukiy/JavSP#8]
有的作品名字太长会无法创建文件夹

感谢作者，支持

**Comment by Yuukiy** [comment]
这个功能是要做的，也做了一个初步的（f18c1b9 ）。但是有木有标题很长的那种给我实际测试一下。。。谢谢

**Comment by ChiotOnAGE** [comment]
> 没有后续反馈

你好，可以尝试一下 `MIUM-672`? 而且如果是用在通过 SMB 挂载的非 NTFS 系统，比如 zfs, 那么 256 的文件名长度限制非常容易就超过了，可否在代码中加入一个可以用来设置最长文件名的参数呢？

**Comment by Yuukiy** [comment]
@ChiotOnAGE 现在是有限制最长路径的参数的：`max_path_len`，不过它是按照字符计数的。后面我加一个选择按字符还是按字节计数的选项吧，目前如果你要用的话可以先把这个参数改得小一些，或者直接从`save_dir`的规则里去掉标题，例如
```ini
save_dir = $actress/$num
```

**Comment by ChiotOnAGE** [comment]
> @ChiotOnAGE 现在是有限制最长路径的配置的：`max_path_len`，不过它是按照字符计数的。后面我加一个选择按字符还是按字节计数的选项吧，目前如果你要用的话可以先把这个参数改得小一些，或者直接从 `save_dir` 的规则里去掉标题，例如
> 
> ```ini
> save_dir = $actress/$num
> ```

是的，建议还是加一个用 byte 还是 character 计算的选项。而且我看 [Wiki](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) 上的说法，很多文件系统（不包括 NTFS）路径长度大多没有限制，而只是限制了文件名长度，目前按照 absolute path 计算的路径长度限制会导致文件名过早被截断。

**Comment by Yuukiy** [comment]
我先关闭这个ticket了，后续可以去#119讨论
