### ISSUE TITLE
刮削时有些片名中包含特殊符号的会报WinError 123错误

### ISSUE THREAD

**Issue by JinShichang** [Yuukiy/JavSP#80]
### 问题详情

建议增加过滤符号功能 防止创建目录错误

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 运行截图（可选）

![QQ截图20220603110307](https://user-images.githubusercontent.com/11838132/171778527-1b1d0475-86fe-4110-afa1-b79035d2ffc2.png)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你是在windows上整理NAS映射过来的文件夹么？整理windows本地的文件夹内的影片会报同样的错误么？

**Comment by JinShichang** [comment]
> 

是的 群晖NAS的smb共享文件夹 本地没有试过

**Comment by JinShichang** [comment]
已解决 经过排查不是符号问题 多次尝试将 最后将max_path_len 改为 160后问题解决
