### ISSUE TITLE
导演的变量名错误

### ISSUE THREAD

**Issue by kenz1025** [Yuukiy/JavSP#85]
### 问题详情

应该是**director**现在的是**directr** ，所以jellyfin里识别不到导演
另外请问下作者要如何配置config才能写入日语的tag？？

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
> 另外请问下作者要如何配置config才能写入日语的tag？？

无法通过配置来实现写入日语的tag，因为各个网站提供的tag不同，基本都是中文日文混杂的tag
