### ISSUE TITLE
希望增加封面图片文件名称自定义选项

### ISSUE THREAD

**Issue by markawonge** [Yuukiy/JavSP#9]
在非emby环境下(如群晖VideoStation)，只能识别Cover.jpg、视频同名文件.jpg，对于多CD视频影片也是如此。
希望作者能够增加自定义选项以方便其他程序调用，谢谢。

例：
#整理完成
  ├─女优A
  │  └─[ABC-100] 刘姥姥大观园のSEX事情
  │          ABC-100 刘姥姥大观园のSEX事情.mp4
  │          ABC-100 刘姥姥大观园のSEX事情.jpg （VideoStation）
  │          ABC-100 刘姥姥大观园のSEX事情-fanart.jpg （Emby/Plex）
  │          ABC-100 刘姥姥大观园のSEX事情-poster.jpg （Emby/Plex）
  │          ABC-100 刘姥姥大观园のSEX事情.nfo （Emby/Plex）
└─女优A，女优B，女优C
      └─[ABC-123] 蛇皮宝宝喜相逢
              ABC-123 蛇皮宝宝喜相逢-CD1.mp4
              ABC-123 蛇皮宝宝喜相逢-CD2.mp4
              ABC-123 蛇皮宝宝喜相逢-CD3.mp4
              ABC-123 蛇皮宝宝喜相逢-fanart.jpg （Emby/Plex）
              ABC-123 蛇皮宝宝喜相逢-poster.jpg （Emby/Plex）
              ABC-123 蛇皮宝宝喜相逢.nfo （Emby/Plex）
              ABC-123 蛇皮宝宝喜相逢-CD1.jpg （VideoStation）
              ABC-123 蛇皮宝宝喜相逢-CD2.jpg （VideoStation）
              ABC-123 蛇皮宝宝喜相逢-CD3.jpg （VideoStation）

**Comment by Yuukiy** [comment]
已添加此功能: b5aafee3 ，需要在配置文件中指明需要video station：
```ini
media_servers = jellyfin,video_station
```
生成的文件夹结构类似这样
```
└─鬼束ちひろ
    └─[ABC-123] 悲伤的声音在背上留下抓印 鬼束ちひろ
            ABC-123-CD1.jpg
            ABC-123-CD1.mp4
            ABC-123-CD1.png
            ABC-123-CD2.jpg
            ABC-123-CD2.mp4
            ABC-123-CD2.png
            ABC-123-CD3.jpg
            ABC-123-CD3.mp4
            ABC-123-CD3.png
            ABC-123-fanart.jpg
            ABC-123-poster.jpg
            ABC-123.nfo
```
不过我没有对应的设备，没法测试实际效果，如果你有用到的话希望能反馈一下是否生效。

**Comment by Yuukiy** [comment]
无后续反馈
