### ISSUE TITLE
扫描挂载群晖的目录出错

### ISSUE THREAD

**Issue by FrankeyLing** [Yuukiy/JavSP#90]
### 问题详情

将群晖通过SMB/Webdav赋予其盘符挂载到Windows，运行JavSP软件，选择挂载盘下任一目录进行影片文件扫描，均会出现re.error:bad character range T-0 at position 4
对Windows本地目录进行扫描时可以正常运行
对通过SMB挂载到本地的另一台Windows电脑的硬盘下的目录进行扫描时可以正常运行
分别尝试了运行打包后的exe文件和通过源代码运行，错误基本完全一致
分别在Windows10 21H1和Windows11 21H2进行了测试，错误基本完全一致

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/9125274/JavSP.log)

### 运行截图（可选）

![image](https://user-images.githubusercontent.com/49284079/179343033-ec3b0432-8359-4c7a-9905-d234d0a45aa5.png)

E:\Softwares\JavSP\JavSP-master>python JavSP.py
请选择要整理的文件夹：Qt: Untested Windows version 10.0 detected!
log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.
Qt: Untested Windows version 10.0 detected!
log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.
Qt: Untested Windows version 10.0 detected!
log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.
Qt: Untested Windows version 10.0 detected!
log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.
Qt: Untested Windows version 10.0 detected!
log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.
I:\TEMP
扫描影片文件...

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
JavSP.py 529 <module>
"E:\Softwares\JavSP\JavSP-master\JavSP.py", line 529
recognized = scan_movies(root)

file.py 66 scan_movies
"E:\Softwares\JavSP\JavSP-master\core\file.py", line 66
pattern = re.compile(prefix + r'\s*([a-z\d])\s*\.\w+$', flags=re.I)

re.py 252 compile
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\re.py", line 252
return _compile(pattern, flags)

re.py 304 _compile
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\re.py", line 304
p = sre_compile.compile(pattern, flags)

sre_compile.py 764 compile
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\sre_compile.py", line 764
p = sre_parse.parse(p, flags)

sre_parse.py 948 parse
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 948
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)

sre_parse.py 443 _parse_sub
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 443
itemsappend(_parse(source, state, verbose, nested + 1,

sre_parse.py 598 _parse
"C:\Users\Frankey\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 598
raise source.error(msg, len(this) + 1 + len(that))

re.error:
bad character range T-0 at position 4

E:\Softwares\JavSP\JavSP-master>

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
ce4ade1444e01aef421df855421ba7b6d0744c2c 应该修复了这个问题，可以稍待用新版本试试
