### ISSUE TITLE
文件名或者路径在有“?”、“、”、“╲”、“/”、“*”、““”、“”“、“<”、“>”、“|”会出现整理失败的情况

### ISSUE THREAD

**Issue by yygtboy** [Yuukiy/JavSP#91]
### 问题详情

感谢作者制作出这么好用的软件，比心 ♥
如果配置中文件夹路径或者是文件名设置中包含$title，例如：save_dir = $num-$title-$date  在获取标题时出现“?”、“、”、“╲”、“/”、“*”、““”、“”“、“<”、“>”、“|” 字符，就会出现整理失败的情况。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
软件正常是会处理特殊字符的。你没有给出影片文件名，我也没法复现。
