### ISSUE TITLE
希望 添加可以自主选择  整理方式路径

### ISSUE THREAD

**Issue by lushutao** [Yuukiy/JavSP#92]
### 功能建议

个人 实际使用一些建议
关于整理文件方式 / 每个人都有自己习惯方式  所以建议添加一些选择项 
1）当前默认模式# 整理完成#-AV大佬名字-【车牌号】（车牌名字简介）-自动整理车牌号信息
2）                      整理完成#-【车牌号】-自动整理车牌号信息
3）                      整理完成#-【AV大佬名字】-自动整理车牌号信息
4）                      整理完成#-自动整理车牌号信息
会代码的人可能很效率就能整理修改 但不会代码的人 还是挺懵逼的
建议 大佬可以给个选项 让大家自行 根据需求来整理文件 
可以借助 Jellyfin  如果使用1 方案 如果不喜欢一个电影 在Jellyfin里面删除 会保留一些多余文件夹 所以想简化一些
文件少的情况 怎么都方便   但一但文件比较多了 整理就比较麻烦一些 
有的人喜欢放在一个文件夹里面 可以直接手动删除 有的人可能喜欢 根据车牌 或者 AV大佬去整理
当然 这是用过的最好的 刮车牌信息的工具 谢谢 
如果有不同建议 大家可以探索一下 

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你可以按照命名规则的wiki实现你自己的整理规则

https://github.com/Yuukiy/JavSP/wiki/NamingRule-%7C-%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99
