### ISSUE TITLE
特定格式番号获取失败

### ISSUE THREAD

**Issue by kenz1025** [Yuukiy/JavSP#93]
### 问题详情

单字母-数字的类似番号都无法提取
core.file:62 ERROR: 无法提取影片番号: 'G:\新建文件夹\新建文件夹\C-2669.mp4'

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
接受单字母+数字的模式的话，可能会很容易匹配到文件名里的广告。暂时可以使用手动的方式指定番号：
`JavSP -m`
这种模式下，遇到无法匹配的番号会提示你手动输入的
