### ISSUE TITLE
很棒的开源，是否考虑增加web ui？

### ISSUE THREAD

**Issue by b1fly** [Yuukiy/JavSP#94]
### 功能建议

数据采集完，需要一个存放并展示的东西，是否考虑做一个简单的展示？例如：django

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
我不是互联网行业的，python已经是我努力的极限了哈哈哈，UI的东西搞不来
