### ISSUE TITLE
报错list index out of range解析网页数据时出现异常: IndexError('list index out of range')

### ISSUE THREAD

**Issue by CapriKev** [Yuukiy/JavSP#97]
### 问题详情

已设置代理，但是仍然提示"list index out of range解析网页数据时出现异常: IndexError('list index out of range')"

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/Yuukiy/JavSP/files/9434983/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
已于 c5df0f120b260b7468eed9e3dd499e11776d9578 修复
