### ISSUE TITLE
可以增加mac版本和docker的支持吗大佬

### ISSUE THREAD

**Issue by yl948** [Yuukiy/JavSP#98]
### 功能建议

建议增加docker和mac版本支持，嘎嘎

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
玩不来docker，最近精力也有限，暂时不考虑。mac版本可以考虑试试从源代码运行

**Comment by blackman-rct** [comment]
> 玩不来docker，最近精力也有限，暂时不考虑。mac版本可以考虑试试从源代码运行

感谢提醒，我在macOS下成功运行源代码版。原版我看依赖文件只有Windows和Linux版，原来在macOS下直接安装Linux版就可以运行。辛苦了～
