### ISSUE TITLE
JAVDB应该是设置哪里失效了，无法爬到数据了，希望作者大大更新

### ISSUE THREAD

**Issue by iancchiu** [Yuukiy/JavSP#99]
### 问题详情

JAVDB应该是设置哪里失效了，设置未仅有JAVBD都无法爬到数据了，希望作者大大更新

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
已于 c5df0f120b260b7468eed9e3dd499e11776d9578 修复
